#!/usr/bin/env bash
# .claude/hooks/generated-guard.sh — PreToolUse guard (Edit|Write|MultiEdit).
#
# Blocks edits to generated or vendored files before they happen. Reads the
# hook JSON on stdin, extracts the target path, and refuses the edit (exit 2,
# message to stderr so Claude sees why) when it matches a protected pattern.
# Exit 0 lets the edit proceed. Paths are matched on their suffix, so this
# works regardless of where the repo is checked out.
#
#   1. editors/tree-sitter-musa/src/{parser.c,grammar.json,node-types.json}
#      are generated by `tree-sitter generate` (see the tree-sitter-grammar
#      skill); hand edits are clobbered on the next generate and desync the
#      grammar from the committed artifacts zed-musa pins by rev.
#   2. target/ holds cargo build output.
#   3. node_modules/ holds vendored npm dependencies.
#   4. packages/musa-web/dist-cdn/ and examples/build-time/out/ are vite
#      build output (prompts 175, 178).
set -euo pipefail

command -v jq >/dev/null 2>&1 || exit 0
input="$(cat)"
file="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"
# No -f check: a Write may target a path that does not exist yet.
[ -n "$file" ] || exit 0

case "$file" in
*/editors/tree-sitter-musa/src/parser.c | */editors/tree-sitter-musa/src/grammar.json | */editors/tree-sitter-musa/src/node-types.json)
  echo "Refusing to edit '$file': it is generated by 'tree-sitter generate' in editors/tree-sitter-musa/. Edit grammar.js, then run 'npm run generate' there and commit all three generated files." >&2
  exit 2
  ;;
*/target/*)
  echo "Refusing to edit '$file': target/ holds cargo build output." >&2
  exit 2
  ;;
*/node_modules/*)
  echo "Refusing to edit '$file': node_modules/ holds vendored npm dependencies." >&2
  exit 2
  ;;
*/packages/musa-web/dist-cdn/* | */packages/musa-web/examples/build-time/out/*)
  echo "Refusing to edit '$file': vite build output (prompts 175, 178). Rebuild with the packages/musa-web build." >&2
  exit 2
  ;;
esac

exit 0
