; Braces are the language's explicit structure, so every braced body folds.
; Comment runs fold in the editor, not the query — a run is not a node.
[
  (piece_declaration)
  (library_declaration)
  (template_declaration)
  (signature_declaration)
  (structure_declaration)
  (data_declaration)
  (score_declaration)
  (part_declaration)
  (voice_declaration)
  (motif_declaration)
  (fragment_declaration)
  (performance_declaration)
  (profile_declaration)
  (settings_block)
  (studio_declaration)
  (patch_declaration)
  (bus_declaration)
  (block)
  (with_clause)
  (grace_statement)
  (mobile_statement)
  (harmony_declaration)
  (music_expression)
  (kernel_quote)
  (match_expression)
  (block_expression)
] @fold
