/* Generated by `musa-au`. Do not edit.
 *
 * Regenerate with `UPDATE_AU_HEADER=1 cargo test -p musa-au`; a currency test
 * fails when this file and the crate disagree. What is trusted at this
 * boundary, and what a caller must guarantee, is in `../TRUST.md`.
 */

#ifndef MUSA_AU_H
#define MUSA_AU_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The version this library was built as. A host bundle and this library are
 * built together, so an extension reads it once at load and refuses rather
 * than rendering through a layout it was not compiled against. */
#define MUSA_AU_ABI_VERSION 2u

/* Event kinds. `data1` and `data2` mean what the comment beside each says. */
#define MUSA_AU_EVENT_NOTE_ON           1u  /* data1 note, data2 attack velocity */
#define MUSA_AU_EVENT_NOTE_OFF          2u  /* data1 note, data2 release velocity */
#define MUSA_AU_EVENT_CONTROLLER        3u  /* data1 controller number, data2 value */
#define MUSA_AU_EVENT_PITCH_BEND        4u  /* data1 low seven bits, data2 high seven */
#define MUSA_AU_EVENT_CHANNEL_PRESSURE  5u  /* data1 pressure */
#define MUSA_AU_EVENT_KEY_PRESSURE      6u  /* data1 note, data2 pressure */
#define MUSA_AU_EVENT_PARAMETER         7u  /* address, value, ramp */

/* Bit zero of a control's flags: the source declares it continuous, so a ramp
 * towards a new value is something the declaration supports. */
#define MUSA_AU_CONTROL_CONTINUOUS      1u

/* The greatest number of outputs one render call may fill. */
#define MUSA_AU_MAX_OUTPUTS             8u

/* One host event, at a sample offset inside the block being rendered.
 *
 * No channel: a Music Device instance is one part of one piece, so which MIDI
 * channel the host used is a routing question and not a musical one. `voice`
 * is the host's own identity for the voice a note-on begins and a note-off
 * ends, because Musa pairs them by identity rather than by pitch. */
typedef struct {
    uint64_t address; /* parameter events only; zero is never an address */
    uint32_t frame;
    uint32_t voice;
    uint32_t ramp;    /* parameter events only; frames to reach `value` */
    float    value;   /* parameter events only */
    uint8_t  kind;
    uint8_t  data1;
    uint8_t  data2;
    uint8_t  reserved; /* must be zero */
} MusaAuEvent;

_Static_assert(sizeof(MusaAuEvent) == 32, "MusaAuEvent size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuEvent, address) == 0, "MusaAuEvent::address moved");
_Static_assert(offsetof(MusaAuEvent, frame) == 8, "MusaAuEvent::frame moved");
_Static_assert(offsetof(MusaAuEvent, voice) == 12, "MusaAuEvent::voice moved");
_Static_assert(offsetof(MusaAuEvent, ramp) == 16, "MusaAuEvent::ramp moved");
_Static_assert(offsetof(MusaAuEvent, value) == 20, "MusaAuEvent::value moved");
_Static_assert(offsetof(MusaAuEvent, kind) == 24, "MusaAuEvent::kind moved");
_Static_assert(offsetof(MusaAuEvent, data1) == 25, "MusaAuEvent::data1 moved");
_Static_assert(offsetof(MusaAuEvent, data2) == 26, "MusaAuEvent::data2 moved");
_Static_assert(offsetof(MusaAuEvent, reserved) == 27, "MusaAuEvent::reserved moved");

/* One exposed control's numbers, as a host builds a parameter from them. The
 * strings beside it are separate accessors: they are borrowed from the
 * preparation and this struct is returned by value. */
typedef struct {
    uint64_t address;
    float    minimum;
    float    maximum;
    float    default_value;
    uint32_t flags;
} MusaAuControl;

_Static_assert(sizeof(MusaAuControl) == 24, "MusaAuControl size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuControl, address) == 0, "MusaAuControl::address moved");
_Static_assert(offsetof(MusaAuControl, minimum) == 8, "MusaAuControl::minimum moved");
_Static_assert(offsetof(MusaAuControl, maximum) == 12, "MusaAuControl::maximum moved");
_Static_assert(offsetof(MusaAuControl, default_value) == 16, "MusaAuControl::default_value moved");
_Static_assert(offsetof(MusaAuControl, flags) == 20, "MusaAuControl::flags moved");

/* Which timeline a schedule's positions are counted on. Never inferred: a
 * processor that guessed between these would be silently deciding whether the
 * host's tempo changes what the piece is. */
#define MUSA_AU_TIMELINE_PIECE          0u  /* seconds, the piece's own schedule */
#define MUSA_AU_TIMELINE_HOST           1u  /* quarter notes on the host's grid */

/* Which reading of the piece a schedule projects. */
#define MUSA_AU_MIDI_SCORE              0u  /* as written */
#define MUSA_AU_MIDI_PERFORMANCE        1u  /* as played */

/* One scheduled MIDI message, at a position on the schedule's timeline. The
 * position is a double because a host compares it against its own sample time
 * or beat position; the conversion from exact rational time happened once, on
 * the control side. */
typedef struct {
    double   position;
    uint32_t part;
    uint8_t  status;
    uint8_t  data1;
    uint8_t  data2;
    uint8_t  reserved; /* must be zero */
} MusaAuScheduleEvent;

_Static_assert(sizeof(MusaAuScheduleEvent) == 16, "MusaAuScheduleEvent size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuScheduleEvent, position) == 0, "MusaAuScheduleEvent::position moved");
_Static_assert(offsetof(MusaAuScheduleEvent, part) == 8, "MusaAuScheduleEvent::part moved");
_Static_assert(offsetof(MusaAuScheduleEvent, status) == 12, "MusaAuScheduleEvent::status moved");
_Static_assert(offsetof(MusaAuScheduleEvent, data1) == 13, "MusaAuScheduleEvent::data1 moved");
_Static_assert(offsetof(MusaAuScheduleEvent, data2) == 14, "MusaAuScheduleEvent::data2 moved");
_Static_assert(offsetof(MusaAuScheduleEvent, reserved) == 15, "MusaAuScheduleEvent::reserved moved");

/* One note sounding across a position: an attack already given, a release
 * still ahead. Both ends are here so a host that seeked into the middle of a
 * held note never searches backwards for either. */
typedef struct {
    double   start;
    double   end;
    uint32_t part;
    uint8_t  status;
    uint8_t  note;
    uint8_t  velocity;
    uint8_t  reserved; /* must be zero */
} MusaAuSpan;

_Static_assert(sizeof(MusaAuSpan) == 24, "MusaAuSpan size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuSpan, start) == 0, "MusaAuSpan::start moved");
_Static_assert(offsetof(MusaAuSpan, end) == 8, "MusaAuSpan::end moved");
_Static_assert(offsetof(MusaAuSpan, part) == 16, "MusaAuSpan::part moved");
_Static_assert(offsetof(MusaAuSpan, status) == 20, "MusaAuSpan::status moved");
_Static_assert(offsetof(MusaAuSpan, note) == 21, "MusaAuSpan::note moved");
_Static_assert(offsetof(MusaAuSpan, velocity) == 22, "MusaAuSpan::velocity moved");
_Static_assert(offsetof(MusaAuSpan, reserved) == 23, "MusaAuSpan::reserved moved");

/* The result of one preparation: an instrument, or why there is not one. */
typedef struct MusaAuPreparation MusaAuPreparation;

/* One piece projected as MIDI, for a host to place on its own timeline. */
typedef struct MusaAuSchedule MusaAuSchedule;

/* A prepared instrument a host may render. */
typedef struct MusaAuInstrument MusaAuInstrument;

uint32_t musa_au_abi_version(void);

/* === Control side: reads files, allocates, takes as long as it takes. === */

/* Compile, verify, and prepare one part's instrument. Never returns null.
 * `piece` may be null, meaning the project's first piece. Release the result
 * with musa_au_preparation_release whether or not it succeeded. */
MusaAuPreparation *musa_au_prepare(const char *project, const char *piece, const char *part, uint32_t sample_rate,
                                   const char *table);

/* Nonzero when the preparation produced an instrument. */
int musa_au_preparation_ok(const MusaAuPreparation *preparation);

/* Why it produced nothing; empty when it succeeded. Borrowed from the
 * preparation and valid only until it is released. */
const char *musa_au_preparation_message(const MusaAuPreparation *preparation);

/* What the instrument was prepared from. Each is borrowed from the
 * preparation and valid only until it is released, and each is empty when the
 * preparation failed. A restored document that does not name the same music
 * and assets was made from a different closure. */
const char *musa_au_preparation_identity_music(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_assets(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_piece(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_part(const MusaAuPreparation *preparation);

/* The MIDI dimensions this instrument's source binds. Anything else the host
 * sends is a loss to report, not an error to raise. */
uint32_t musa_au_preparation_input_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_input(const MusaAuPreparation *preparation, uint32_t index);

/* The source-declared controls this instrument exposes as host parameters.
 * These are exactly the controls the source declares public: a DSP node, a
 * graph edge, or a host convenience knob is never one of them. Each string is
 * borrowed from the preparation. `musa_au_preparation_control` writes `out`
 * and returns nonzero, or writes nothing and returns zero past the end. */
uint32_t musa_au_preparation_control_count(const MusaAuPreparation *preparation);
int musa_au_preparation_control(const MusaAuPreparation *preparation, uint32_t index, MusaAuControl *out);
const char *musa_au_preparation_control_identity(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_display(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_summary(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_kind(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_update_rate(const MusaAuPreparation *preparation, uint32_t index);

/* Declared controls this boundary could not carry, each as one sentence. */
uint32_t musa_au_preparation_loss_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_loss(const MusaAuPreparation *preparation, uint32_t index);

/* The complete parameter-address table, for the host document to carry back
 * to the next musa_au_prepare. */
const char *musa_au_preparation_control_table(const MusaAuPreparation *preparation);

/* The outputs the source declares for this part. Index zero is the main
 * output and is always present; the rest are the declared points this part
 * reaches. The role is 0 main, 1 a part output, 2 a declared bus. */
uint32_t musa_au_preparation_output_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_output(const MusaAuPreparation *preparation, uint32_t index);
uint32_t musa_au_preparation_output_role(const MusaAuPreparation *preparation, uint32_t index);

/* Take the instrument out, leaving the preparation empty. Null if the
 * preparation failed or was already taken. The instrument outlives the
 * preparation. */
MusaAuInstrument *musa_au_preparation_take(MusaAuPreparation *preparation);

void musa_au_preparation_release(MusaAuPreparation *preparation);

/* Release an instrument. This destroys a prepared graph, which is exactly
 * what a render callback may not do: retire a replaced plan on a worker. */
void musa_au_instrument_release(MusaAuInstrument *instrument);

/* === Render side: no allocation, no lock, no I/O, no logging, no
 * destruction. === */

/* Render one block into two preallocated channel buffers. `events` must be
 * sorted by frame; `left` and `right` each address `frames` writable floats
 * and must not alias. */
void musa_au_render(MusaAuInstrument *instrument, const MusaAuEvent *events, uint32_t count, float *left,
                    float *right, uint32_t frames);

/* Render one block into every negotiated output. `channels` holds two
 * pointers per output — left then right, bus zero first — and `channel_count`
 * is how many are supplied; an odd count renders nothing. Bus zero is exactly
 * what musa_au_render would have produced. */
void musa_au_render_outputs(MusaAuInstrument *instrument, const MusaAuEvent *events, uint32_t count,
                            float *const *channels, uint32_t channel_count, uint32_t frames);

/* Return the instrument to its prepared silence. */
void musa_au_reset(MusaAuInstrument *instrument);

/* Bounded counters a host may read while rendering. */
uint32_t musa_au_unbound_events(const MusaAuInstrument *instrument);
uint64_t musa_au_rendered_frames(const MusaAuInstrument *instrument);

/* === The MIDI Processor side: one piece, read by position. === */

/* Open one piece as a finite schedule of MIDI messages. Never returns null.
 * `piece` may be null, meaning the project's first piece. `mode` is
 * MUSA_AU_MIDI_*, `timeline` is MUSA_AU_TIMELINE_*, and a value this library
 * does not know is refused rather than defaulted. Control side: this reads
 * files and allocates. Release with musa_au_schedule_release. */
MusaAuSchedule *musa_au_open_schedule(const char *project, const char *piece, uint32_t mode, uint32_t timeline);

/* Nonzero when the piece became a schedule; otherwise why it did not. The
 * message is borrowed from the schedule. */
int musa_au_schedule_ok(const MusaAuSchedule *schedule);
const char *musa_au_schedule_message(const MusaAuSchedule *schedule);

/* What the schedule was made from, and what it is counted on. Each string is
 * borrowed from the schedule and valid only until it is released. */
const char *musa_au_schedule_identity_music(const MusaAuSchedule *schedule);
const char *musa_au_schedule_identity_assets(const MusaAuSchedule *schedule);
const char *musa_au_schedule_identity_piece(const MusaAuSchedule *schedule);
uint32_t musa_au_schedule_timeline(const MusaAuSchedule *schedule);

/* The parts the piece projects. The name is borrowed; the channel is the one
 * every message of that part carries, and is 16 past the end. */
uint32_t musa_au_schedule_part_count(const MusaAuSchedule *schedule);
const char *musa_au_schedule_part_name(const MusaAuSchedule *schedule, uint32_t index);
uint32_t musa_au_schedule_part_channel(const MusaAuSchedule *schedule, uint32_t index);

/* What this projection could not carry, each as one sentence. */
uint32_t musa_au_schedule_loss_count(const MusaAuSchedule *schedule);
const char *musa_au_schedule_loss(const MusaAuSchedule *schedule, uint32_t index);

/* The whole piece: how many messages it is, and where it ends. */
uint32_t musa_au_schedule_count(const MusaAuSchedule *schedule);
double musa_au_schedule_extent(const MusaAuSchedule *schedule);

/* === Render side of the processor: binary searches into immutable arrays.
 * No allocation, no lock, no I/O, no logging, no destruction, and no cursor
 * to replay after a seek. === */

/* The index of the first message at or after `position`. A block is the
 * half-open range [lower_bound(start), lower_bound(end)), so a message on a
 * boundary is emitted by the later block, exactly once. */
uint32_t musa_au_schedule_lower_bound(const MusaAuSchedule *schedule, double position);

/* One message. Writes `out` and returns nonzero, or writes nothing and
 * returns zero past the end. */
int musa_au_schedule_event(const MusaAuSchedule *schedule, uint32_t index, MusaAuScheduleEvent *out);

/* The notes sounding across `position`, for a host that has just seeked.
 * Writes up to `capacity` of them and returns how many there were, which may
 * be more than it wrote. A note attacked exactly at `position` is not one of
 * these: the block starting there emits its own note-on. */
uint32_t musa_au_schedule_active(MusaAuSchedule *schedule, double position, MusaAuSpan *out, uint32_t capacity);

/* Instrumentation: the index the active-note search starts at. A harness
 * reads it to see that seeking into the middle does not begin at note one. */
uint32_t musa_au_schedule_active_scan_start(const MusaAuSchedule *schedule, double position);

void musa_au_schedule_release(MusaAuSchedule *schedule);

#ifdef __cplusplus
}
#endif

#endif /* MUSA_AU_H */
