//! Deterministic sources for the elaboration migration workloads.
//!
//! Run `UPDATE_ELABORATION_BASELINE=1 cargo test -p musa-compiler
//! --test suite` to refresh the committed fixtures.

#![allow(clippy::expect_used)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use musa_compiler::{CompileOptions, SourceDocument, compile};

type Result = std::result::Result<(), Box<dyn std::error::Error>>;

const UPDATE: &str = "UPDATE_ELABORATION_BASELINE";

fn word(index: usize) -> String {
    let first = char::from(b'a'.saturating_add(u8::try_from(index / 26).unwrap_or(0)));
    let second = char::from(b'a'.saturating_add(u8::try_from(index % 26).unwrap_or(0)));
    if index < 26 {
        second.to_string()
    } else {
        format!("{first}{second}")
    }
}

fn repository() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn write_or_compare(path: &Path, contents: &str) -> Result {
    let current = std::fs::read_to_string(path).ok();
    if current.as_deref() == Some(contents) {
        return Ok(());
    }
    if current.is_some() && std::env::var_os(UPDATE).is_none() {
        return Err(format!(
            "{} is stale — rerun with {UPDATE}=1 and commit the result",
            path.display()
        )
        .into());
    }
    std::fs::create_dir_all(path.parent().unwrap_or_else(|| Path::new(".")))?;
    std::fs::write(path, contents)?;
    Ok(())
}

fn open_shape() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Current syntax only: many reusable bodies under changing contexts.\n\n\
         piece \"Open Shape Baseline\" {\n\
             tempo 1/4 = 96;\n\
             meter 4/4;\n\
             key c major;\n\n",
    );
    for index in 0..16 {
        let root = ["c", "d", "e", "f", "g", "a", "b"]
            .get(index % 7)
            .copied()
            .unwrap_or("c");
        let name = word(index);
        let _ = writeln!(source, "    motif cell_{name}() {{ {root}4/4 e4/4 g4/4 c5/4 }}");
    }
    source.push_str("\n    score {\n");
    for (part, voice, clef) in [("flute", "upper", "treble"), ("cello", "lower", "bass")] {
        let _ = writeln!(source, "        part {part} {{");
        let _ = writeln!(source, "            clef {clef};");
        let _ = writeln!(source, "            voice {voice} {{");
        for index in 0..16 {
            let name = word(index);
            if index == 4 {
                source.push_str("                key g major;\n");
            } else if index == 8 {
                source.push_str("                key f major;\n");
            } else if index == 12 {
                source.push_str("                key c major;\n");
            }
            let _ = writeln!(source, "                use cell_{name}();");
        }
        source.push_str("            }\n        }\n");
    }
    source.push_str("    }\n}\n");
    source
}

fn higher_order_shape() -> String {
    String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // The same 128 notes as open-shape, through nested current-syntax transforms.\n\n\
         piece \"Higher Order Shape Baseline\" {\n\
             tempo 1/4 = 96;\n\
             meter 4/4;\n\
             key c major;\n\n\
             motif cell() { c4/4 e4/4 g4/4 c5/4 }\n\n\
             score {\n\
                 part flute {\n\
                     clef treble;\n\
                     voice upper {\n\
                         repeat 16 {\n\
                             stretch 1 { retrograde { retrograde { use cell(); } } }\n\
                         }\n\
                     }\n\
                 }\n\
                 part cello {\n\
                     clef bass;\n\
                     voice lower {\n\
                         repeat 16 {\n\
                             invert around c4 { invert around c4 { use cell(); } }\n\
                         }\n\
                     }\n\
                 }\n\
             }\n\
         }\n",
    )
}

fn declaration_library(index: usize) -> String {
    let mut source = String::from("\n");
    for item in 0..16 {
        let library = word(index);
        let item = word(item);
        let _ = writeln!(
            source,
            "    motif imported_{library}_{item}() {{ c4/4 d4/4 e4/4 f4/4 }}"
        );
    }
    source.push('\n');
    source
}

fn declaration_heavy() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Many small local and imported declarations, most deliberately unused.\n\n\
         piece \"Declaration Heavy Baseline\" {\n",
    );
    for index in 0..4 {
        let _ = writeln!(source, "    import \"elaboration-libraries/library-{index}.musa\";");
    }
    source.push_str("    tempo 1/4 = 96;\n    meter 4/4;\n    key c major;\n\n");
    for index in 0..48 {
        let name = word(index);
        let _ = writeln!(source, "    motif local_{name}() {{ c4/4 d4/4 e4/4 f4/4 }}");
    }
    for index in 0..16 {
        let name = word(index);
        let _ = writeln!(source, "    fragment fragment_{name} {{ g4/4 a4/4 b4/4 c5/4 }}");
    }
    source.push_str(
        "\n    score {\n\
             part ensemble {\n\
                 voice line {\n\
                     use local_a();\n\
                     use imported_a_a();\n\
                     mobile { fragment_a; fragment_b; }\n\
                 }\n\
             }\n\
         }\n\
         }\n",
    );
    source
}

fn audio_bridge() -> String {
    String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Score marks, performance profiles, studio intent, scheduling, and DSP in one fixture.\n\n\
         piece \"Audio Bridge Baseline\" {\n\
             tempo 1/4 = 60;\n\
             meter 4/4;\n\
             key c major;\n\n\
             performance {\n\
                 profile reeds {\n\
                     mark staccato { gate = 0.55; attack = 8 ms; }\n\
                     mark accent { gate = 1; attack = 2 ms; }\n\
                     dynamic p { amplitude = 0.25; }\n\
                     dynamic f { amplitude = 0.8; }\n\
                 }\n\
                 profile strings {\n\
                     mark staccato { gate = 0.7; attack = 15 ms; }\n\
                     mark accent { gate = 1; attack = 5 ms; }\n\
                     dynamic p { amplitude = 0.2; }\n\
                     dynamic f { amplitude = 0.7; }\n\
                 }\n\
             }\n\n\
             score {\n\
                 part oboe {\n\
                     profile reeds;\n\
                     voice melody {\n\
                         dynamic p;\n\
                         crescendo to f { c5/4 staccato d5/4 e5/4 > f5/4 }\n\
                     }\n\
                 }\n\
                 part viola {\n\
                     profile strings;\n\
                     voice countermelody {\n\
                         dynamic f;\n\
                         diminuendo to p { c4/4 > g3/4 a3/4 staccato f3/4 }\n\
                     }\n\
                 }\n\
             }\n\n\
             instrument reed conforms note_instrument {\n\
                 implementation graph { oscillator(sine) |> lowpass(cutoff: 1800 Hz, resonance: 0.7) |> output; }\n\
             }\n\
             instrument bow conforms note_instrument {\n\
                 implementation graph { oscillator(sine, ratio: 0.5) |> envelope(adsr(attack: 15 ms, release: 300 ms)) |> output; }\n\
             }\n\n\
             studio {\n\
                 bus hall { reverb(room: 0.55, mix: 0.25); }\n\
                 lfo = oscillator(sine, frequency: 0.5 Hz) |> scale(200 Hz);\n\
                 modulate lfo -> reed.lowpass.cutoff;\n\
                 assign oboe -> reed;\n\
                 assign viola -> bow;\n\
                 route oboe -> master;\n\
                 route viola -> master;\n\
                 send oboe -> hall at -18 dB;\n\
                 send viola -> hall at -20 dB;\n\
                 route hall -> master;\n\
             }\n\
         }\n",
    )
}

/// The seven letters, walked by index so a generator can spell a step
/// without a scale.
const LETTERS: [&str; 7] = ["c", "d", "e", "f", "g", "a", "b"];

fn letter(index: usize) -> &'static str {
    LETTERS.get(index % 7).copied().unwrap_or("c")
}

/// Prompt 127's total-core workload: a call chain deeper than any piece would
/// write, a fold over a list two orders of magnitude longer than a phrase, and
/// a named function value.
///
/// It denotes eight notes. That is the point: everything expensive here is the
/// expression layer, so a regression in the evaluator cannot hide behind note
/// production.
fn core_pressure() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Total-core pressure: deep calls, a long fold, and a named function value.\n\n\
         piece \"Core Pressure Baseline\" {\n\
             import std::core;\n\
             import std::list;\n\
             tempo 1/4 = 96;\n\
             meter 4/4;\n\
             key c major;\n\n\
             fn keep(index: Nat, accumulator: Nat) -> Nat { accumulator }\n\
             fn depth_0(seed: Nat) -> Nat { range(1).fold_from_start(seed, fn (carried, index) { keep(index, carried) }) }\n",
    );
    for index in 1_usize..64 {
        let below = index.saturating_sub(1);
        let _ = writeln!(
            source,
            "    fn depth_{index}(seed: Nat) -> Nat {{ depth_{below}(seed) }}"
        );
    }
    source.push_str(
        "\n    let deep: Nat = depth_63(0);\n\
         \x20   let counted: List(Nat) = naturals(512);\n\
         \x20   let folded: Nat = counted.fold_from_start(0, fn (carried, one) { keep(one, carried) });\n\n\
         \x20   let raise: EventTrack(WrittenTime) -> EventTrack(WrittenTime) = fn (line: EventTrack(WrittenTime)) -> EventTrack(WrittenTime) { transpose(P8, line) };\n\
         \x20   let subject: EventTrack(WrittenTime) = music { c4/4 d4/4 e4/4 f4/4 };\n\
         \x20   let answer: EventTrack(WrittenTime) = compose_music(raise, retrograde, subject);\n\n\
         \x20   score {\n\
         \x20       part strings {\n\
         \x20           voice line {\n\
         \x20               use subject;\n\
         \x20               use answer;\n\
         \x20           }\n\
         \x20       }\n\
         \x20   }\n\
         }\n",
    );
    source
}

/// Prompt 127's expansion workload: a record of material built eight times,
/// each value folded into a voice by a function that repeats it under two
/// scales, plus one source import.
///
/// Every note here carries a use site, a repeat index, a scale context, and a
/// motif application in its origin, which is what makes it the provenance
/// workload as well as the expansion one. The fixture keeps its name from when
/// the eight were functor instances (prompt 162 deleted that layer), so the
/// measurements in `06-elaboration-baseline.md` stay comparable.
fn template_pressure() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // A record built eight times, nested use sites, scale contexts, and an import.\n\n\
         import std::context;\n\n\
         record CellMaterial {\n\
         \x20   cell: EventTrack(WrittenTime);\n\
         \x20   answer: EventTrack(WrittenTime) -> EventTrack(WrittenTime);\n\
         }\n\n\
         fn cell_material(home: TonalContext, lift: Interval) -> CellMaterial {\n\
         \x20   CellMaterial {\n\
         \x20       cell = music {\n\
         \x20           in scale home.collection {\n\
         \x20               c5/8\n\
         \x20               d5/8\n\
         \x20               e5/8\n\
         \x20               f5/8\n\
         \x20           }\n\
         \x20       },\n\
         \x20       answer = fn (line: EventTrack(WrittenTime)) -> EventTrack(WrittenTime) { transpose(lift, line) },\n\
         \x20   }\n\
         }\n\n",
    );
    const LIFTS: [&str; 8] = ["P5", "P4", "M3", "m3", "M2", "m7", "P8", "M6"];
    for index in 0..8 {
        let context = if index % 2 == 0 { "c_major" } else { "a_natural_minor" };
        let lift = LIFTS.get(index).copied().unwrap_or("P5");
        let name = word(index);
        let _ = writeln!(
            source,
            "let cell_{name}: CellMaterial = cell_material({context}, {lift});"
        );
    }
    source.push_str(
        "\nfn strand(\n\
         \x20   subject: EventTrack(WrittenTime),\n\
         \x20   transform: EventTrack(WrittenTime) -> EventTrack(WrittenTime),\n\
         ) -> EventTrack(WrittenTime) {\n\
         \x20   music {\n\
         \x20       repeat 4 {\n\
         \x20           in scale c major { use subject; (c5 step 1)/8 (c5 step 2)/8 }\n\
         \x20           in scale c dorian { use transform(subject); (c5 step 1)/8 (c5 step 2)/8 }\n\
         \x20       }\n\
         \x20   }\n\
         }\n\n\
         let home: Key = key c major;\n\n\
         piece \"Template Pressure Baseline\" {\n\
         \x20   import \"elaboration-libraries/library-0.musa\";\n\n\
         \x20   tempo 1/4 = 96;\n\
         \x20   meter 4/4;\n\
         \x20   key home;\n\n\
         \x20   score {\n\
         \x20       part keyboard {\n\
         \x20           voice imported {\n\
         \x20               repeat 4 {\n\
         \x20                   use imported_a_a();\n\
         \x20               }\n\
         \x20           }\n\n",
    );
    for index in 0..8 {
        let name = word(index);
        let _ = writeln!(
            source,
            "            voice strand_{name} {{\n\
             \x20               use strand(cell_{name}.cell, cell_{name}.answer);\n\
             \x20           }}"
        );
    }
    source.push_str(
        "        }\n\
         \x20   }\n\
         }\n",
    );
    source
}

/// Prompt 127's analysis workload: sixty-four bars of four-part harmony over a
/// repeating functional progression, with the tonal-construction vocabulary
/// declared above it.
///
/// Its warnings are deliberate. A progression returns to its tonic, so bars
/// repeat note for note and the lint pass says so; the lint pass is part of
/// what a keystroke pays, and a workload that avoided tripping it would
/// measure a compiler nobody runs.
fn analysis_pressure() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Four-part harmony for the analysis stages, over constructed tonal vocabulary.\n\n\
         piece \"Analysis Pressure Baseline\" {\n\
             import std::harmony;\n\
             import std::scale;\n\
             import std::tonal::harmony;\n\
             import std::voicing;\n\n\
             tempo 1/4 = 72;\n\
             meter 4/4;\n\
             key c major;\n\n\
             let home: Scale = scale c major;\n\
             let five: Option(Roman) = triad_numeral(5);\n\
             let five_seventh: Option(Roman) = seventh_numeral(5);\n\n\
             fn in_home(written: Option(Roman)) -> Option(ChordClass) {\n\
                 match written {\n\
                     None -> None,\n\
                     Some(numbered) -> numeral_chord(home, numbered),\n\
                 }\n\
             }\n\n\
             let tonic: Option(ChordClass) = in_home(triad_numeral(1));\n\
             let subdominant: Option(ChordClass) = in_home(triad_numeral(4));\n\
             let dominant: Option(ChordClass) = in_home(five);\n\
             let dominant_seventh: Option(ChordClass) = in_home(five_seventh);\n\n\
             score {\n",
    );
    // One chord per bar. The soprano walks a figure over each chord so the
    // upper part is a line rather than a block, and the figure rotates every
    // sixteen bars so the four sections are not four copies.
    const PROGRESSION: [usize; 16] = [1, 4, 5, 1, 6, 2, 5, 1, 4, 1, 5, 6, 2, 5, 1, 1];
    const FIGURES: [[usize; 4]; 4] = [[2, 3, 4, 2], [2, 1, 3, 2], [4, 3, 2, 4], [2, 4, 3, 2]];
    for (name, clef, offset, octave) in [
        ("soprano", "treble", 2, 5),
        ("alto", "treble", 4, 4),
        ("tenor", "bass", 2, 3),
        ("bass", "bass", 0, 2),
    ] {
        let _ = writeln!(source, "        part {name} {{");
        let _ = writeln!(source, "            clef {clef};");
        source.push_str("            voice line {\n");
        for section in 0..4 {
            for degree in PROGRESSION {
                if name == "soprano" {
                    let figure = FIGURES.get(section).copied().unwrap_or([2, 3, 4, 2]);
                    source.push_str("                |");
                    for step in figure {
                        let _ = write!(
                            source,
                            " {}{octave}/4",
                            letter(degree.saturating_sub(1).saturating_add(step))
                        );
                    }
                    source.push('\n');
                } else {
                    let _ = writeln!(
                        source,
                        "                | {}{octave}/1",
                        letter(degree.saturating_sub(1).saturating_add(offset))
                    );
                }
            }
        }
        source.push_str("            }\n        }\n");
    }
    source.push_str("    }\n}\n");
    source
}

/// Prompt 127's quotation workload: thirty-two typed holes bound inside one
/// events quote, each placed three ways.
fn events_pressure() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Many typed quote holes in one assembled term.\n\n\
         piece \"Events Pressure Baseline\" {\n\
             meter 4/4;\n\
             key c major;\n\n",
    );
    for index in 0..32 {
        let _ = writeln!(
            source,
            "    let cell_{index}: EventTrack(WrittenTime) = music {{ {}4/8 {}4/8 {}4/8 {}4/8 }};",
            letter(index),
            letter(index.saturating_add(2)),
            letter(index.saturating_add(4)),
            letter(index.saturating_add(6)),
        );
    }
    source.push_str("\n    let assembled: EventTrack(WrittenTime) = events EventTrack[WrittenTime, ScoreFact] {\n");
    for index in 0..32 {
        let _ = writeln!(source, "        let held_{index} = ${{cell_{index}}} in");
    }
    source.push_str("        together {\n");
    for index in 0..32 {
        let _ = writeln!(source, "            shift by {index}/2 held_{index};");
        let _ = writeln!(
            source,
            "            shift by {index}/2 restrict from 1/4 to 1/2 held_{index};"
        );
        let _ = writeln!(
            source,
            "            shift by {index}/2 ${{stretch(1/2, cell_{index})}};"
        );
    }
    source.push_str("            track 16 {\n");
    for index in 0..32 {
        let _ = writeln!(
            source,
            "                occurrence \"note {}2 1/2\" from {index}/2 to {}/2;",
            letter(index),
            index.saturating_add(1)
        );
    }
    source.push_str(
        "            };\n\
         \x20       }\n\
         \x20   };\n\n\
         \x20   score {\n\
         \x20       part ensemble {\n\
         \x20           voice line {\n\
         \x20               use assembled;\n\
         \x20           }\n\
         \x20       }\n\
         \x20   }\n\
         }\n",
    );
    source
}

/// Prompt 127's events-document workload: sixteen phrases of thirty-two
/// occurrences, each placed three ways — a `.musa.events` file an order of
/// magnitude larger than any generated from `examples/`.
fn events_document_pressure() -> String {
    let mut source = String::from(
        "% musa-events-3\n\
         % generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs\n\
         events \"Events Document Pressure Baseline\" {\n\
         \x20 composition main : EventTrack[WrittenTime, ScoreFact] =\n",
    );
    for phrase in 0_usize..16 {
        let _ = writeln!(source, "    let phrase_{phrase} = track 8 {{");
        for note in 0..32_usize {
            let quarter = i64::try_from(note).unwrap_or(0);
            let onset = num_rational::Ratio::new(quarter, 4);
            let end = num_rational::Ratio::new(quarter.saturating_add(1), 4);
            let _ = writeln!(
                source,
                "        occurrence \"voice 0 0 note {}4 1/4 [0:0 #1]\" from {} to {};",
                letter(phrase.saturating_add(note)),
                ratio(onset),
                ratio(end),
            );
        }
        source.push_str("      }\n    in\n");
    }
    source.push_str("    together {\n");
    for phrase in 0..16 {
        source.push_str("      follow {\n");
        let _ = writeln!(source, "        phrase_{phrase};");
        let _ = writeln!(source, "        shift by 1/2 phrase_{phrase};");
        let _ = writeln!(source, "        restrict from 0 to 4 phrase_{phrase}");
        source.push_str("      };\n");
    }
    source.push_str("    };\n}\n");
    source
}

/// A rational as the event track prints it: a whole number has no denominator.
fn ratio(value: num_rational::Ratio<i64>) -> String {
    if *value.denom() == 1 {
        value.numer().to_string()
    } else {
        format!("{}/{}", value.numer(), value.denom())
    }
}

#[test]
fn elaboration_baseline_fixtures_are_current() -> Result {
    let root = repository().join("tests/fixtures");
    for (name, source) in [
        ("open-shape.musa", open_shape()),
        ("higher-order-shape.musa", higher_order_shape()),
        ("declaration-heavy.musa", declaration_heavy()),
        ("audio-bridge.musa", audio_bridge()),
        ("core-pressure.musa", core_pressure()),
        ("template-pressure.musa", template_pressure()),
        ("analysis-pressure.musa", analysis_pressure()),
        ("events-pressure.musa", events_pressure()),
        ("events-pressure.musa.events", events_document_pressure()),
    ] {
        write_or_compare(&root.join(name), &source)?;
    }
    for index in 0..4 {
        write_or_compare(
            &root.join(format!("elaboration-libraries/library-{index}.musa")),
            &declaration_library(index),
        )?;
    }
    Ok(())
}

/// Every prompt-127 workload compiles, and each one denotes what it claims.
///
/// A benchmark on a fixture that does not compile measures the diagnostic
/// path, silently and forever. The note counts are here for the same reason
/// the benchmark prints occurrence counts: a row of a timing table cannot be
/// read without the size of the workload behind it.
///
/// Ignored because the five-workload sweep is a 0.65 s generated pressure test,
/// not because any case remains red. On prompt 165's finished cost table it
/// compiles all five and verifies 8, 400, 448, 288, and 80 score events. The
/// fast suite still covers the same compile-then-count contract through
/// `the_sharing_shapes_compile_and_denote_what_they_claim` and
/// `shape_pair_has_the_same_denoted_note_count`; this test defers only the much
/// broader evaluator, expansion, analysis, and events-document workload.
#[test]
#[ignore = "0.65 s generated pressure sweep; fast laws cover compile-then-count, this test covers the full five-workload envelope"]
fn the_pressure_workloads_compile_and_denote_what_they_claim() {
    let mut imported = CompileOptions::default();
    imported.imports.insert(
        "tests/fixtures/elaboration-libraries/library-0.musa".to_owned(),
        declaration_library(0),
    );
    for (name, source, options, notes) in [
        ("core-pressure", core_pressure(), CompileOptions::default(), 8),
        ("template-pressure", template_pressure(), imported, 16 + 8 * 48),
        (
            "analysis-pressure",
            analysis_pressure(),
            CompileOptions::default(),
            64 * 4 + 64 * 3,
        ),
        // Each cell is four notes and a window of [1/4, 1/2] keeps two of
        // them, so the *track* carries thirty-two held, thirty-two diminished,
        // thirty-two restricted, and one raw phrase: 352 occurrences, which is
        // what `musa events` prints. A voice denotes fewer, and the difference
        // is the workload's own doing rather than a loss. The restricted copy
        // is shifted by the same `index/2` as the copy it was cut from, so its
        // two notes land on two of the held notes at the same onset with the
        // same spelling, and a voice merges what sounds together at one onset
        // into one event. Thirty-two cells times two notes is the sixty-four
        // that merge away.
        (
            "events-pressure",
            events_pressure(),
            CompileOptions::default(),
            32 * 4 + 32 * 4 + 32,
        ),
        (
            "events-document-pressure",
            events_document_pressure(),
            CompileOptions::default(),
            // Whole, shifted, and windowed to its first half — 80 occurrences a
            // phrase, and sixteen phrases, so 1,280 in the track. One phrase's
            // worth reaches a voice, for the same reason as above and more
            // completely: every occurrence in the document names `voice 0 0`,
            // every phrase starts at 0 on the same quarter-note grid, and the
            // sixteen `follow`s sit inside one `together`. So all sixteen land
            // on one another and merge onset by onset. The size of this
            // workload is the 1,280 the document holds; the 80 is what one
            // voice is left denoting.
            32 + 32 + 16,
        ),
    ] {
        let document = SourceDocument::new(source, format!("tests/fixtures/{name}.musa"));
        let compilation = compile(&document, &options);
        let errors: Vec<&str> = compilation
            .diagnostics()
            .iter()
            .filter(|diagnostic| diagnostic.severity == musa_score::Severity::Error)
            .map(|diagnostic| diagnostic.message.as_str())
            .collect();
        assert!(errors.is_empty(), "{name} does not compile: {errors:?}");
        let score = compilation.snapshot().expect("a pressure workload denotes a score");
        let counted: usize = score
            .parts()
            .iter()
            .flat_map(|(_, part)| part.voices())
            .map(|(_, voice)| voice.events().len())
            .sum();
        assert_eq!(counted, notes, "{name} denotes a different number of events");
    }
}

/// Every generated sharing shape compiles, and each one denotes what it
/// claims.
///
/// The committed pressure fixtures have had this guarantee since they were
/// written; the *generated* sharing pieces did not, and the gap was not
/// theoretical. `sharing_source` went on emitting a parameter default for
/// fifty-three commits after the language dropped defaults, so the benchmark
/// binary panicked in its own preamble and every P0–S2 measurement was
/// unreachable — including the two that had regressed past the 10% gate in
/// `docs/rules/language/06-elaboration-baseline.md`. A benchmark nobody can run is a
/// gate nobody is holding.
///
/// One representative call count is enough: what this protects is that the
/// three shapes still *are* musa, not the shape of their scaling curve, which
/// is what the benchmark itself measures.
#[test]
fn the_sharing_shapes_compile_and_denote_what_they_claim() {
    use musa_compiler::bench::{Sharing, sharing_source};

    const CALLS: usize = 8;
    const BODY: usize = 16;
    for (shape, notes) in [
        // Every call denotes the body and nothing else.
        (Sharing::Identical, CALLS * BODY),
        // The argument is the first note; the body follows it.
        (Sharing::Distinct, CALLS * (1 + BODY)),
        // The same music, with the argument-independent tail written beside
        // the parameterized head rather than inside it.
        (Sharing::Hoisted, CALLS * (1 + BODY)),
    ] {
        let name = format!("benches/sharing-{shape:?}.musa");
        let document = SourceDocument::new(sharing_source(shape, CALLS, BODY), &name);
        let compilation = compile(&document, &CompileOptions::default());
        let errors: Vec<&str> = compilation
            .diagnostics()
            .iter()
            .filter(|diagnostic| diagnostic.severity == musa_score::Severity::Error)
            .map(|diagnostic| diagnostic.message.as_str())
            .collect();
        assert!(errors.is_empty(), "{shape:?} does not compile: {errors:?}");
        let score = compilation.snapshot().expect("a sharing workload denotes a score");
        let counted: usize = score
            .parts()
            .iter()
            .flat_map(|(_, part)| part.voices())
            .map(|(_, voice)| voice.events().len())
            .sum();
        assert_eq!(counted, notes, "{shape:?} denotes a different number of events");
    }
}

#[test]
fn shape_pair_has_the_same_denoted_note_count() {
    let count = |source: String, name: &str| {
        let compilation = compile(&SourceDocument::new(source, name), &CompileOptions::default());
        let score = compilation.snapshot().expect("generated fixture compiles");
        score
            .parts()
            .iter()
            .flat_map(|(_, part)| part.voices())
            .map(|(_, voice)| voice.events().len())
            .sum::<usize>()
    };
    assert_eq!(count(open_shape(), "open-shape"), 128);
    assert_eq!(count(higher_order_shape(), "higher-order-shape"), 128);
}
