//! The C header, generated from this crate rather than kept beside it.
//!
//! A hand-maintained header for a hand-written ABI is two declarations of one
//! thing, and the pair drifts the first time a field moves. So the header is
//! *derived*: [`header`] writes it, a currency test regenerates
//! `include/musa_au.h` and compares byte for byte, and the Xcode target
//! compiles the committed file. The static assertions in it are what makes
//! that a real check rather than a tidy one — they are computed here from
//! `size_of` and `offset_of` on the Rust types, so a C compiler that disagrees
//! fails the build.
//!
//! Regenerate with `UPDATE_AU_HEADER=1 cargo test -p musa-au`.

use std::fmt::Write as _;
use std::mem::{offset_of, size_of};

use crate::abi::{
    MUSA_AU_ABI_VERSION, MUSA_AU_EVENT_CHANNEL_PRESSURE, MUSA_AU_EVENT_CONTROLLER, MUSA_AU_EVENT_KEY_PRESSURE,
    MUSA_AU_EVENT_NOTE_OFF, MUSA_AU_EVENT_NOTE_ON, MUSA_AU_EVENT_PITCH_BEND, MusaAuEvent,
};

/// The exact text of `include/musa_au.h`.
#[must_use]
pub fn header() -> String {
    let mut out = String::with_capacity(8192);
    let _ = write!(
        out,
        r#"/* Generated by `musa-au`. Do not edit.
 *
 * Regenerate with `UPDATE_AU_HEADER=1 cargo test -p musa-au`; a currency test
 * fails when this file and the crate disagree. What is trusted at this
 * boundary, and what a caller must guarantee, is in `../TRUST.md`.
 */

#ifndef MUSA_AU_H
#define MUSA_AU_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* The version this library was built as. A host bundle and this library are
 * built together, so an extension reads it once at load and refuses rather
 * than rendering through a layout it was not compiled against. */
#define MUSA_AU_ABI_VERSION {version}u

/* Event kinds. `data1` and `data2` mean what the comment beside each says. */
#define MUSA_AU_EVENT_NOTE_ON           {note_on}u  /* data1 note, data2 attack velocity */
#define MUSA_AU_EVENT_NOTE_OFF          {note_off}u  /* data1 note, data2 release velocity */
#define MUSA_AU_EVENT_CONTROLLER        {controller}u  /* data1 controller number, data2 value */
#define MUSA_AU_EVENT_PITCH_BEND        {bend}u  /* data1 low seven bits, data2 high seven */
#define MUSA_AU_EVENT_CHANNEL_PRESSURE  {pressure}u  /* data1 pressure */
#define MUSA_AU_EVENT_KEY_PRESSURE      {key}u  /* data1 note, data2 pressure */

/* One host event, at a sample offset inside the block being rendered.
 *
 * No channel: a Music Device instance is one part of one piece, so which MIDI
 * channel the host used is a routing question and not a musical one. `voice`
 * is the host's own identity for the voice a note-on begins and a note-off
 * ends, because Musa pairs them by identity rather than by pitch. */
typedef struct {{
    uint32_t frame;
    uint32_t voice;
    uint8_t  kind;
    uint8_t  data1;
    uint8_t  data2;
    uint8_t  reserved; /* must be zero */
}} MusaAuEvent;

_Static_assert(sizeof(MusaAuEvent) == {event_size}, "MusaAuEvent size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuEvent, frame) == {off_frame}, "MusaAuEvent::frame moved");
_Static_assert(offsetof(MusaAuEvent, voice) == {off_voice}, "MusaAuEvent::voice moved");
_Static_assert(offsetof(MusaAuEvent, kind) == {off_kind}, "MusaAuEvent::kind moved");
_Static_assert(offsetof(MusaAuEvent, data1) == {off_data1}, "MusaAuEvent::data1 moved");
_Static_assert(offsetof(MusaAuEvent, data2) == {off_data2}, "MusaAuEvent::data2 moved");
_Static_assert(offsetof(MusaAuEvent, reserved) == {off_reserved}, "MusaAuEvent::reserved moved");

/* The result of one preparation: an instrument, or why there is not one. */
typedef struct MusaAuPreparation MusaAuPreparation;

/* A prepared instrument a host may render. */
typedef struct MusaAuInstrument MusaAuInstrument;

uint32_t musa_au_abi_version(void);

/* === Control side: reads files, allocates, takes as long as it takes. === */

/* Compile, verify, and prepare one part's instrument. Never returns null.
 * `piece` may be null, meaning the project's first piece. Release the result
 * with musa_au_preparation_release whether or not it succeeded. */
MusaAuPreparation *musa_au_prepare(const char *project, const char *piece, const char *part, uint32_t sample_rate);

/* Nonzero when the preparation produced an instrument. */
int musa_au_preparation_ok(const MusaAuPreparation *preparation);

/* Why it produced nothing; empty when it succeeded. Borrowed from the
 * preparation and valid only until it is released. */
const char *musa_au_preparation_message(const MusaAuPreparation *preparation);

/* What the instrument was prepared from. Each is borrowed from the
 * preparation and valid only until it is released, and each is empty when the
 * preparation failed. A restored document that does not name the same music
 * and assets was made from a different closure. */
const char *musa_au_preparation_identity_music(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_assets(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_piece(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_part(const MusaAuPreparation *preparation);

/* The MIDI dimensions this instrument's source binds. Anything else the host
 * sends is a loss to report, not an error to raise. */
uint32_t musa_au_preparation_input_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_input(const MusaAuPreparation *preparation, uint32_t index);

/* Take the instrument out, leaving the preparation empty. Null if the
 * preparation failed or was already taken. The instrument outlives the
 * preparation. */
MusaAuInstrument *musa_au_preparation_take(MusaAuPreparation *preparation);

void musa_au_preparation_release(MusaAuPreparation *preparation);

/* Release an instrument. This destroys a prepared graph, which is exactly
 * what a render callback may not do: retire a replaced plan on a worker. */
void musa_au_instrument_release(MusaAuInstrument *instrument);

/* === Render side: no allocation, no lock, no I/O, no logging, no
 * destruction. === */

/* Render one block into two preallocated channel buffers. `events` must be
 * sorted by frame; `left` and `right` each address `frames` writable floats
 * and must not alias. */
void musa_au_render(MusaAuInstrument *instrument, const MusaAuEvent *events, uint32_t count, float *left,
                    float *right, uint32_t frames);

/* Return the instrument to its prepared silence. */
void musa_au_reset(MusaAuInstrument *instrument);

/* Bounded counters a host may read while rendering. */
uint32_t musa_au_unbound_events(const MusaAuInstrument *instrument);
uint64_t musa_au_rendered_frames(const MusaAuInstrument *instrument);

#ifdef __cplusplus
}}
#endif

#endif /* MUSA_AU_H */
"#,
        version = MUSA_AU_ABI_VERSION,
        note_on = MUSA_AU_EVENT_NOTE_ON,
        note_off = MUSA_AU_EVENT_NOTE_OFF,
        controller = MUSA_AU_EVENT_CONTROLLER,
        bend = MUSA_AU_EVENT_PITCH_BEND,
        pressure = MUSA_AU_EVENT_CHANNEL_PRESSURE,
        key = MUSA_AU_EVENT_KEY_PRESSURE,
        event_size = size_of::<MusaAuEvent>(),
        off_frame = offset_of!(MusaAuEvent, frame),
        off_voice = offset_of!(MusaAuEvent, voice),
        off_kind = offset_of!(MusaAuEvent, kind),
        off_data1 = offset_of!(MusaAuEvent, data1),
        off_data2 = offset_of!(MusaAuEvent, data2),
        off_reserved = offset_of!(MusaAuEvent, reserved),
    );
    out
}
