//! The C header, generated from this crate rather than kept beside it.
//!
//! A hand-maintained header for a hand-written ABI is two declarations of one
//! thing, and the pair drifts the first time a field moves. So the header is
//! *derived*: [`header`] writes it, a currency test regenerates
//! `include/musa_au.h` and compares byte for byte, and the Xcode target
//! compiles the committed file. The static assertions in it are what makes
//! that a real check rather than a tidy one — they are computed here from
//! `size_of` and `offset_of` on the Rust types, so a C compiler that disagrees
//! fails the build.
//!
//! Regenerate with `UPDATE_AU_HEADER=1 cargo test -p musa-au`.

use std::fmt::Write as _;
use std::mem::{offset_of, size_of};

use crate::abi::{
    MUSA_AU_ABI_VERSION, MUSA_AU_CONTROL_CONTINUOUS, MUSA_AU_EVENT_CHANNEL_PRESSURE, MUSA_AU_EVENT_CONTROLLER,
    MUSA_AU_EVENT_KEY_PRESSURE, MUSA_AU_EVENT_NOTE_OFF, MUSA_AU_EVENT_NOTE_ON, MUSA_AU_EVENT_PARAMETER,
    MUSA_AU_EVENT_PITCH_BEND, MUSA_AU_MAX_OUTPUTS, MusaAuControl, MusaAuEvent,
};
use crate::schedule::{
    MUSA_AU_MIDI_PERFORMANCE, MUSA_AU_MIDI_SCORE, MUSA_AU_TIMELINE_HOST, MUSA_AU_TIMELINE_PIECE, MusaAuScheduleEvent,
    MusaAuSpan,
};

/// The exact text of `include/musa_au.h`.
#[must_use]
pub fn header() -> String {
    let mut out = String::with_capacity(8192);
    let _ = write!(
        out,
        r#"/* Generated by `musa-au`. Do not edit.
 *
 * Regenerate with `UPDATE_AU_HEADER=1 cargo test -p musa-au`; a currency test
 * fails when this file and the crate disagree. What is trusted at this
 * boundary, and what a caller must guarantee, is in `../TRUST.md`.
 */

#ifndef MUSA_AU_H
#define MUSA_AU_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* The version this library was built as. A host bundle and this library are
 * built together, so an extension reads it once at load and refuses rather
 * than rendering through a layout it was not compiled against. */
#define MUSA_AU_ABI_VERSION {version}u

/* Event kinds. `data1` and `data2` mean what the comment beside each says. */
#define MUSA_AU_EVENT_NOTE_ON           {note_on}u  /* data1 note, data2 attack velocity */
#define MUSA_AU_EVENT_NOTE_OFF          {note_off}u  /* data1 note, data2 release velocity */
#define MUSA_AU_EVENT_CONTROLLER        {controller}u  /* data1 controller number, data2 value */
#define MUSA_AU_EVENT_PITCH_BEND        {bend}u  /* data1 low seven bits, data2 high seven */
#define MUSA_AU_EVENT_CHANNEL_PRESSURE  {pressure}u  /* data1 pressure */
#define MUSA_AU_EVENT_KEY_PRESSURE      {key}u  /* data1 note, data2 pressure */
#define MUSA_AU_EVENT_PARAMETER         {parameter}u  /* address, value, ramp */

/* Bit zero of a control's flags: the source declares it continuous, so a ramp
 * towards a new value is something the declaration supports. */
#define MUSA_AU_CONTROL_CONTINUOUS      {continuous}u

/* The greatest number of outputs one render call may fill. */
#define MUSA_AU_MAX_OUTPUTS             {max_outputs}u

/* One host event, at a sample offset inside the block being rendered.
 *
 * No channel: a Music Device instance is one part of one piece, so which MIDI
 * channel the host used is a routing question and not a musical one. `voice`
 * is the host's own identity for the voice a note-on begins and a note-off
 * ends, because Musa pairs them by identity rather than by pitch. */
typedef struct {{
    uint64_t address; /* parameter events only; zero is never an address */
    uint32_t frame;
    uint32_t voice;
    uint32_t ramp;    /* parameter events only; frames to reach `value` */
    float    value;   /* parameter events only */
    uint8_t  kind;
    uint8_t  data1;
    uint8_t  data2;
    uint8_t  reserved; /* must be zero */
}} MusaAuEvent;

_Static_assert(sizeof(MusaAuEvent) == {event_size}, "MusaAuEvent size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuEvent, address) == {off_address}, "MusaAuEvent::address moved");
_Static_assert(offsetof(MusaAuEvent, frame) == {off_frame}, "MusaAuEvent::frame moved");
_Static_assert(offsetof(MusaAuEvent, voice) == {off_voice}, "MusaAuEvent::voice moved");
_Static_assert(offsetof(MusaAuEvent, ramp) == {off_ramp}, "MusaAuEvent::ramp moved");
_Static_assert(offsetof(MusaAuEvent, value) == {off_value}, "MusaAuEvent::value moved");
_Static_assert(offsetof(MusaAuEvent, kind) == {off_kind}, "MusaAuEvent::kind moved");
_Static_assert(offsetof(MusaAuEvent, data1) == {off_data1}, "MusaAuEvent::data1 moved");
_Static_assert(offsetof(MusaAuEvent, data2) == {off_data2}, "MusaAuEvent::data2 moved");
_Static_assert(offsetof(MusaAuEvent, reserved) == {off_reserved}, "MusaAuEvent::reserved moved");

/* One exposed control's numbers, as a host builds a parameter from them. The
 * strings beside it are separate accessors: they are borrowed from the
 * preparation and this struct is returned by value. */
typedef struct {{
    uint64_t address;
    float    minimum;
    float    maximum;
    float    default_value;
    uint32_t flags;
}} MusaAuControl;

_Static_assert(sizeof(MusaAuControl) == {control_size}, "MusaAuControl size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuControl, address) == {c_address}, "MusaAuControl::address moved");
_Static_assert(offsetof(MusaAuControl, minimum) == {c_minimum}, "MusaAuControl::minimum moved");
_Static_assert(offsetof(MusaAuControl, maximum) == {c_maximum}, "MusaAuControl::maximum moved");
_Static_assert(offsetof(MusaAuControl, default_value) == {c_default}, "MusaAuControl::default_value moved");
_Static_assert(offsetof(MusaAuControl, flags) == {c_flags}, "MusaAuControl::flags moved");

/* Which timeline a schedule's positions are counted on. Never inferred: a
 * processor that guessed between these would be silently deciding whether the
 * host's tempo changes what the piece is. */
#define MUSA_AU_TIMELINE_PIECE          {timeline_piece}u  /* seconds, the piece's own schedule */
#define MUSA_AU_TIMELINE_HOST           {timeline_host}u  /* quarter notes on the host's grid */

/* Which reading of the piece a schedule projects. */
#define MUSA_AU_MIDI_SCORE              {midi_score}u  /* as written */
#define MUSA_AU_MIDI_PERFORMANCE        {midi_performance}u  /* as played */

/* One scheduled MIDI message, at a position on the schedule's timeline. The
 * position is a double because a host compares it against its own sample time
 * or beat position; the conversion from exact rational time happened once, on
 * the control side. */
typedef struct {{
    double   position;
    uint32_t part;
    uint8_t  status;
    uint8_t  data1;
    uint8_t  data2;
    uint8_t  reserved; /* must be zero */
}} MusaAuScheduleEvent;

_Static_assert(sizeof(MusaAuScheduleEvent) == {event2_size}, "MusaAuScheduleEvent size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuScheduleEvent, position) == {e2_position}, "MusaAuScheduleEvent::position moved");
_Static_assert(offsetof(MusaAuScheduleEvent, part) == {e2_part}, "MusaAuScheduleEvent::part moved");
_Static_assert(offsetof(MusaAuScheduleEvent, status) == {e2_status}, "MusaAuScheduleEvent::status moved");
_Static_assert(offsetof(MusaAuScheduleEvent, data1) == {e2_data1}, "MusaAuScheduleEvent::data1 moved");
_Static_assert(offsetof(MusaAuScheduleEvent, data2) == {e2_data2}, "MusaAuScheduleEvent::data2 moved");
_Static_assert(offsetof(MusaAuScheduleEvent, reserved) == {e2_reserved}, "MusaAuScheduleEvent::reserved moved");

/* One note sounding across a position: an attack already given, a release
 * still ahead. Both ends are here so a host that seeked into the middle of a
 * held note never searches backwards for either. */
typedef struct {{
    double   start;
    double   end;
    uint32_t part;
    uint8_t  status;
    uint8_t  note;
    uint8_t  velocity;
    uint8_t  reserved; /* must be zero */
}} MusaAuSpan;

_Static_assert(sizeof(MusaAuSpan) == {span_size}, "MusaAuSpan size disagrees with the Rust definition");
_Static_assert(offsetof(MusaAuSpan, start) == {s_start}, "MusaAuSpan::start moved");
_Static_assert(offsetof(MusaAuSpan, end) == {s_end}, "MusaAuSpan::end moved");
_Static_assert(offsetof(MusaAuSpan, part) == {s_part}, "MusaAuSpan::part moved");
_Static_assert(offsetof(MusaAuSpan, status) == {s_status}, "MusaAuSpan::status moved");
_Static_assert(offsetof(MusaAuSpan, note) == {s_note}, "MusaAuSpan::note moved");
_Static_assert(offsetof(MusaAuSpan, velocity) == {s_velocity}, "MusaAuSpan::velocity moved");
_Static_assert(offsetof(MusaAuSpan, reserved) == {s_reserved}, "MusaAuSpan::reserved moved");

/* The result of one preparation: an instrument, or why there is not one. */
typedef struct MusaAuPreparation MusaAuPreparation;

/* One piece projected as MIDI, for a host to place on its own timeline. */
typedef struct MusaAuSchedule MusaAuSchedule;

/* A prepared instrument a host may render. */
typedef struct MusaAuInstrument MusaAuInstrument;

uint32_t musa_au_abi_version(void);

/* === Control side: reads files, allocates, takes as long as it takes. === */

/* Compile, verify, and prepare one part's instrument. Never returns null.
 * `piece` may be null, meaning the project's first piece. Release the result
 * with musa_au_preparation_release whether or not it succeeded. */
MusaAuPreparation *musa_au_prepare(const char *project, const char *piece, const char *part, uint32_t sample_rate,
                                   const char *table);

/* Nonzero when the preparation produced an instrument. */
int musa_au_preparation_ok(const MusaAuPreparation *preparation);

/* Why it produced nothing; empty when it succeeded. Borrowed from the
 * preparation and valid only until it is released. */
const char *musa_au_preparation_message(const MusaAuPreparation *preparation);

/* What the instrument was prepared from. Each is borrowed from the
 * preparation and valid only until it is released, and each is empty when the
 * preparation failed. A restored document that does not name the same music
 * and assets was made from a different closure. */
const char *musa_au_preparation_identity_music(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_assets(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_piece(const MusaAuPreparation *preparation);
const char *musa_au_preparation_identity_part(const MusaAuPreparation *preparation);

/* The MIDI dimensions this instrument's source binds. Anything else the host
 * sends is a loss to report, not an error to raise. */
uint32_t musa_au_preparation_input_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_input(const MusaAuPreparation *preparation, uint32_t index);

/* The source-declared controls this instrument exposes as host parameters.
 * These are exactly the controls the source declares public: a DSP node, a
 * graph edge, or a host convenience knob is never one of them. Each string is
 * borrowed from the preparation. `musa_au_preparation_control` writes `out`
 * and returns nonzero, or writes nothing and returns zero past the end. */
uint32_t musa_au_preparation_control_count(const MusaAuPreparation *preparation);
int musa_au_preparation_control(const MusaAuPreparation *preparation, uint32_t index, MusaAuControl *out);
const char *musa_au_preparation_control_identity(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_display(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_summary(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_kind(const MusaAuPreparation *preparation, uint32_t index);
const char *musa_au_preparation_control_update_rate(const MusaAuPreparation *preparation, uint32_t index);

/* Declared controls this boundary could not carry, each as one sentence. */
uint32_t musa_au_preparation_loss_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_loss(const MusaAuPreparation *preparation, uint32_t index);

/* The complete parameter-address table, for the host document to carry back
 * to the next musa_au_prepare. */
const char *musa_au_preparation_control_table(const MusaAuPreparation *preparation);

/* The outputs the source declares for this part. Index zero is the main
 * output and is always present; the rest are the declared points this part
 * reaches. The role is 0 main, 1 a part output, 2 a declared bus. */
uint32_t musa_au_preparation_output_count(const MusaAuPreparation *preparation);
const char *musa_au_preparation_output(const MusaAuPreparation *preparation, uint32_t index);
uint32_t musa_au_preparation_output_role(const MusaAuPreparation *preparation, uint32_t index);

/* Take the instrument out, leaving the preparation empty. Null if the
 * preparation failed or was already taken. The instrument outlives the
 * preparation. */
MusaAuInstrument *musa_au_preparation_take(MusaAuPreparation *preparation);

void musa_au_preparation_release(MusaAuPreparation *preparation);

/* Release an instrument. This destroys a prepared graph, which is exactly
 * what a render callback may not do: retire a replaced plan on a worker. */
void musa_au_instrument_release(MusaAuInstrument *instrument);

/* === Render side: no allocation, no lock, no I/O, no logging, no
 * destruction. === */

/* Render one block into two preallocated channel buffers. `events` must be
 * sorted by frame; `left` and `right` each address `frames` writable floats
 * and must not alias. */
void musa_au_render(MusaAuInstrument *instrument, const MusaAuEvent *events, uint32_t count, float *left,
                    float *right, uint32_t frames);

/* Render one block into every negotiated output. `channels` holds two
 * pointers per output — left then right, bus zero first — and `channel_count`
 * is how many are supplied; an odd count renders nothing. Bus zero is exactly
 * what musa_au_render would have produced. */
void musa_au_render_outputs(MusaAuInstrument *instrument, const MusaAuEvent *events, uint32_t count,
                            float *const *channels, uint32_t channel_count, uint32_t frames);

/* Return the instrument to its prepared silence. */
void musa_au_reset(MusaAuInstrument *instrument);

/* Bounded counters a host may read while rendering. */
uint32_t musa_au_unbound_events(const MusaAuInstrument *instrument);
uint64_t musa_au_rendered_frames(const MusaAuInstrument *instrument);

/* === The MIDI Processor side: one piece, read by position. === */

/* Open one piece as a finite schedule of MIDI messages. Never returns null.
 * `piece` may be null, meaning the project's first piece. `mode` is
 * MUSA_AU_MIDI_*, `timeline` is MUSA_AU_TIMELINE_*, and a value this library
 * does not know is refused rather than defaulted. Control side: this reads
 * files and allocates. Release with musa_au_schedule_release. */
MusaAuSchedule *musa_au_open_schedule(const char *project, const char *piece, uint32_t mode, uint32_t timeline);

/* Nonzero when the piece became a schedule; otherwise why it did not. The
 * message is borrowed from the schedule. */
int musa_au_schedule_ok(const MusaAuSchedule *schedule);
const char *musa_au_schedule_message(const MusaAuSchedule *schedule);

/* What the schedule was made from, and what it is counted on. Each string is
 * borrowed from the schedule and valid only until it is released. */
const char *musa_au_schedule_identity_music(const MusaAuSchedule *schedule);
const char *musa_au_schedule_identity_assets(const MusaAuSchedule *schedule);
const char *musa_au_schedule_identity_piece(const MusaAuSchedule *schedule);
uint32_t musa_au_schedule_timeline(const MusaAuSchedule *schedule);

/* The parts the piece projects. The name is borrowed; the channel is the one
 * every message of that part carries, and is 16 past the end. */
uint32_t musa_au_schedule_part_count(const MusaAuSchedule *schedule);
const char *musa_au_schedule_part_name(const MusaAuSchedule *schedule, uint32_t index);
uint32_t musa_au_schedule_part_channel(const MusaAuSchedule *schedule, uint32_t index);

/* What this projection could not carry, each as one sentence. */
uint32_t musa_au_schedule_loss_count(const MusaAuSchedule *schedule);
const char *musa_au_schedule_loss(const MusaAuSchedule *schedule, uint32_t index);

/* The whole piece: how many messages it is, and where it ends. */
uint32_t musa_au_schedule_count(const MusaAuSchedule *schedule);
double musa_au_schedule_extent(const MusaAuSchedule *schedule);

/* === Render side of the processor: binary searches into immutable arrays.
 * No allocation, no lock, no I/O, no logging, no destruction, and no cursor
 * to replay after a seek. === */

/* The index of the first message at or after `position`. A block is the
 * half-open range [lower_bound(start), lower_bound(end)), so a message on a
 * boundary is emitted by the later block, exactly once. */
uint32_t musa_au_schedule_lower_bound(const MusaAuSchedule *schedule, double position);

/* One message. Writes `out` and returns nonzero, or writes nothing and
 * returns zero past the end. */
int musa_au_schedule_event(const MusaAuSchedule *schedule, uint32_t index, MusaAuScheduleEvent *out);

/* The notes sounding across `position`, for a host that has just seeked.
 * Writes up to `capacity` of them and returns how many there were, which may
 * be more than it wrote. A note attacked exactly at `position` is not one of
 * these: the block starting there emits its own note-on. */
uint32_t musa_au_schedule_active(MusaAuSchedule *schedule, double position, MusaAuSpan *out, uint32_t capacity);

/* Instrumentation: the index the active-note search starts at. A harness
 * reads it to see that seeking into the middle does not begin at note one. */
uint32_t musa_au_schedule_active_scan_start(const MusaAuSchedule *schedule, double position);

void musa_au_schedule_release(MusaAuSchedule *schedule);

#ifdef __cplusplus
}}
#endif

#endif /* MUSA_AU_H */
"#,
        version = MUSA_AU_ABI_VERSION,
        note_on = MUSA_AU_EVENT_NOTE_ON,
        note_off = MUSA_AU_EVENT_NOTE_OFF,
        controller = MUSA_AU_EVENT_CONTROLLER,
        bend = MUSA_AU_EVENT_PITCH_BEND,
        pressure = MUSA_AU_EVENT_CHANNEL_PRESSURE,
        key = MUSA_AU_EVENT_KEY_PRESSURE,
        parameter = MUSA_AU_EVENT_PARAMETER,
        continuous = MUSA_AU_CONTROL_CONTINUOUS,
        max_outputs = MUSA_AU_MAX_OUTPUTS,
        event_size = size_of::<MusaAuEvent>(),
        off_address = offset_of!(MusaAuEvent, address),
        off_ramp = offset_of!(MusaAuEvent, ramp),
        off_value = offset_of!(MusaAuEvent, value),
        control_size = size_of::<MusaAuControl>(),
        c_address = offset_of!(MusaAuControl, address),
        c_minimum = offset_of!(MusaAuControl, minimum),
        c_maximum = offset_of!(MusaAuControl, maximum),
        c_default = offset_of!(MusaAuControl, default_value),
        c_flags = offset_of!(MusaAuControl, flags),
        off_frame = offset_of!(MusaAuEvent, frame),
        off_voice = offset_of!(MusaAuEvent, voice),
        off_kind = offset_of!(MusaAuEvent, kind),
        off_data1 = offset_of!(MusaAuEvent, data1),
        off_data2 = offset_of!(MusaAuEvent, data2),
        off_reserved = offset_of!(MusaAuEvent, reserved),
        timeline_piece = MUSA_AU_TIMELINE_PIECE,
        timeline_host = MUSA_AU_TIMELINE_HOST,
        midi_score = MUSA_AU_MIDI_SCORE,
        midi_performance = MUSA_AU_MIDI_PERFORMANCE,
        event2_size = size_of::<MusaAuScheduleEvent>(),
        e2_position = offset_of!(MusaAuScheduleEvent, position),
        e2_part = offset_of!(MusaAuScheduleEvent, part),
        e2_status = offset_of!(MusaAuScheduleEvent, status),
        e2_data1 = offset_of!(MusaAuScheduleEvent, data1),
        e2_data2 = offset_of!(MusaAuScheduleEvent, data2),
        e2_reserved = offset_of!(MusaAuScheduleEvent, reserved),
        span_size = size_of::<MusaAuSpan>(),
        s_start = offset_of!(MusaAuSpan, start),
        s_end = offset_of!(MusaAuSpan, end),
        s_part = offset_of!(MusaAuSpan, part),
        s_status = offset_of!(MusaAuSpan, status),
        s_note = offset_of!(MusaAuSpan, note),
        s_velocity = offset_of!(MusaAuSpan, velocity),
        s_reserved = offset_of!(MusaAuSpan, reserved),
    );
    out
}
