[package]
description = "Thin CLI over musa-project"
edition.workspace = true
license.workspace = true
name = "musa-cli"
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
miette = { version = "7", features = ["fancy"] }
musa-project = { workspace = true }
thiserror = "2"

[dev-dependencies]
insta = "1"
