[package]
description = "Thin CLI over musa-project"
name = "musa-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
miette = { version = "7", features = ["fancy"] }
musa-project = { path = "../musa-project" }
thiserror = "2"
