//! The wire types the webview sends in, and the one it gets back on failure.
//!
//! These are the shell's own types, not re-exported internals: the command
//! surface is allowed to grow by adding a field here, and `musa-project` is
//! never bent into a shape that exists only for a webview. Their TypeScript
//! is generated by `ts-rs` (`cargo test -p musa-desktop`), so the two sides
//! cannot drift.
//!
//! The snapshot travels the other way and is `musa-project`'s own
//! serialization — see the module documentation on [`crate::session`] for why
//! mirroring it here would create the drift this rule exists to prevent.

use std::path::PathBuf;

use musa_project::{
    ContainerKind, EditCommand, ExportRequest, GeneratedEditMode, GroupEdit, GroupIntent, HeaderField, InsertAt,
    NoteSpec, ProjectCommand, ProjectError, ReviewAction, ReviewAudition, Span, StudioEdit, Template, TextEdit,
    TransportRequest, Utf16Offsets,
};
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::session::Request;

/// The command palette's preview of the exact project-owned barline plan.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(tag = "status", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum BarlinePreviewDto {
    Rewrite {
        revision: u64,
        inserted: usize,
        summary: String,
    },
    AlreadyBarred,
}

impl From<Option<&musa_project::BarlineRewrite>> for BarlinePreviewDto {
    fn from(rewrite: Option<&musa_project::BarlineRewrite>) -> Self {
        match rewrite {
            Some(rewrite) => Self::Rewrite {
                revision: rewrite.revision().0,
                inserted: rewrite.inserted(),
                summary: rewrite.summary(),
            },
            None => Self::AlreadyBarred,
        }
    }
}

/// A range of the source, in UTF-16 code units.
///
/// The webview's measure, not Rust's — the same one the spans in the snapshot
/// arrive in, so an edit can be built from a diagnostic without converting
/// anything. [`crate::session`] restates it in bytes before the session
/// applies it; see [`crate::offsets`] for why the boundary is here.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct SpanDto {
    pub start: u32,
    pub end: u32,
}

impl From<SpanDto> for Span {
    fn from(span: SpanDto) -> Self {
        Self {
            start: span.start,
            end: span.end,
        }
    }
}

/// One replacement against the current source.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct TextEditDto {
    pub span: SpanDto,
    pub replacement: String,
}

impl From<TextEditDto> for TextEdit {
    fn from(edit: TextEditDto) -> Self {
        Self::new(edit.span.into(), edit.replacement)
    }
}

/// What the user just did to the document.
///
/// Undo and redo are here rather than on `ProjectCommand` because the session
/// exposes them as history navigation, not as edits; from the webview's side
/// they are the same kind of request and belong on the same call.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum CommandDto {
    #[serde(rename_all = "camelCase")]
    SetSource {
        source: String,
    },
    #[serde(rename_all = "camelCase")]
    ApplyEdits {
        edits: Vec<TextEditDto>,
    },
    #[serde(rename_all = "camelCase")]
    EditScore {
        edit: EditDto,
    },
    #[serde(rename_all = "camelCase")]
    EditStudio {
        edit: StudioEditDto,
    },
    Format,
    #[serde(rename_all = "camelCase")]
    InsertBarlines {
        revision: u64,
    },
    /// Commit one previewed group transformation, once.
    #[serde(rename_all = "camelCase")]
    ApplyGroupEdit {
        plan: u64,
        revision: u64,
    },
    Save,
    /// Take the work a crash left behind and make it the source.
    RestoreRecovery,
    /// Decline it, and stop being asked.
    DiscardRecovery,
    Undo,
    Redo,
    /// Read the open work again.
    ///
    /// The number is the webview's because a performance is a *label*, not a
    /// musical fact: the composer picks it, types it, and comes back to it.
    /// Everything the number means is the compiler's.
    #[serde(rename_all = "camelCase")]
    NewPerformance {
        performance: u64,
    },
    /// Keep one decision, so the next performance leaves it alone.
    #[serde(rename_all = "camelCase")]
    Keep {
        decision: String,
    },
    /// Let it go back to being drawn.
    #[serde(rename_all = "camelCase")]
    Release {
        decision: String,
    },
}

/// What to do when the edited event came out of an expansion (roadmap §9).
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum GeneratedEditModeDto {
    /// Rewrite the motif; every occurrence changes.
    EditDefinition,
    /// Give this occurrence its own copy.
    Specialize,
}

impl From<GeneratedEditModeDto> for GeneratedEditMode {
    fn from(mode: GeneratedEditModeDto) -> Self {
        match mode {
            GeneratedEditModeDto::EditDefinition => Self::EditDefinition,
            GeneratedEditModeDto::Specialize => Self::Specialize,
        }
    }
}

/// One musical command against a selection (roadmap §11).
///
/// Five commands rather than one, because they are five different musical
/// questions: writing a value on every note, scaling the rhythm that is
/// already there, walking the staff, changing the sign, and moving by an
/// interval are not variants of "change the notes" (OMT ch. 009–012, 016).
/// A webview that offered one and a parameter would be deciding which of
/// them the composer meant.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum GroupIntentDto {
    /// Write this duration on every selected event.
    #[serde(rename_all = "camelCase")]
    SetEachDuration { duration: String },
    /// Multiply every selected duration by this factor.
    #[serde(rename_all = "camelCase")]
    ScaleDurations { ratio: String },
    /// Move every selected pitch this many staff steps, sign unchanged.
    #[serde(rename_all = "camelCase")]
    MoveDiatonically { steps: i32 },
    /// Move every selected pitch this many semitones up the accidental
    /// ladder, notehead unchanged.
    #[serde(rename_all = "camelCase")]
    ShiftAccidentals { steps: i32 },
    /// Transpose every selected pitch by an interval the composer spelled.
    #[serde(rename_all = "camelCase")]
    TransposeBy { interval: String },
}

impl From<GroupIntentDto> for GroupIntent {
    fn from(intent: GroupIntentDto) -> Self {
        match intent {
            GroupIntentDto::SetEachDuration { duration } => Self::SetEachDuration { duration },
            GroupIntentDto::ScaleDurations { ratio } => Self::ScaleDurations { ratio },
            GroupIntentDto::MoveDiatonically { steps } => Self::MoveDiatonically { steps },
            GroupIntentDto::ShiftAccidentals { steps } => Self::ShiftAccidentals { steps },
            GroupIntentDto::TransposeBy { interval } => Self::TransposeBy { interval },
        }
    }
}

/// A selection and what to do to it.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct GroupEditDto {
    /// The engraved event ids the composer selected, in any order.
    pub events: Vec<String>,
    pub intent: GroupIntentDto,
    pub mode: GeneratedEditModeDto,
}

impl From<GroupEditDto> for GroupEdit {
    fn from(edit: GroupEditDto) -> Self {
        Self {
            events: edit.events,
            intent: edit.intent.into(),
            mode: edit.mode.into(),
        }
    }
}

/// One statement the transformation would rewrite, with what depends on it.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct GroupDefinitionDto {
    pub definition: SpanDto,
    pub motif: Option<String>,
    pub occurrences: Vec<String>,
    pub selected: Vec<String>,
    pub events: Vec<String>,
    pub before: String,
    pub after: String,
}

/// One bar that ends up holding something else.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct GroupBarEffectDto {
    pub part: String,
    pub voice: String,
    pub bar: u32,
    /// Written content before and after, spelled as the composer writes a
    /// duration (`1/4`, `3/8`) rather than as a decimal.
    pub before: String,
    pub after: String,
}

/// The preview a composer accepts or cancels.
///
/// Everything in it was computed by the code that would apply it, so the
/// panel is showing the transaction rather than a second guess at it. The
/// plan is named by an identity that applying consumes.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct GroupEditPlanDto {
    pub plan: u64,
    pub revision: u64,
    pub summary: String,
    /// Every event that changes, selected or not.
    pub changed: Vec<String>,
    /// The selected events this command does not apply to.
    pub unchanged: Vec<String>,
    pub definitions: Vec<GroupDefinitionDto>,
    pub bars: Vec<GroupBarEffectDto>,
    /// What the compiler still says about the candidate source. Never an
    /// error: a transformation that would not compile is refused rather than
    /// previewed.
    pub warnings: Vec<String>,
    /// Whether the same selection could be written onto its call instead.
    pub specializable: bool,
}

impl GroupEditPlanDto {
    /// Restate one plan in the webview's measure.
    ///
    /// The offsets are the *current* source's, which is the source the plan
    /// describes: a plan from another revision is refused before it reaches
    /// here (`03-interaction.md` §7).
    pub(crate) fn new(plan: &musa_project::GroupEditPlan, offsets: &Utf16Offsets) -> Self {
        Self {
            plan: plan.id(),
            revision: plan.revision().0,
            summary: plan.summary().to_owned(),
            changed: plan.changed().to_vec(),
            unchanged: plan.unchanged().to_vec(),
            definitions: plan
                .definitions()
                .iter()
                .map(|definition| GroupDefinitionDto {
                    definition: SpanDto {
                        start: offsets.to_utf16(definition.definition.start),
                        end: offsets.to_utf16(definition.definition.end),
                    },
                    motif: definition.motif.clone(),
                    occurrences: definition.occurrences.clone(),
                    selected: definition.selected.clone(),
                    events: definition.events.clone(),
                    before: definition.before.clone(),
                    after: definition.after.clone(),
                })
                .collect(),
            bars: plan
                .bars()
                .iter()
                .map(|bar| GroupBarEffectDto {
                    part: bar.part.clone(),
                    voice: bar.voice.clone(),
                    bar: bar.bar,
                    before: bar.before.to_string(),
                    after: bar.after.to_string(),
                })
                .collect(),
            warnings: plan
                .diagnostics()
                .iter()
                .map(|diagnostic| diagnostic.message.clone())
                .collect(),
            specializable: plan.specializable(),
        }
    }
}

/// Where a newly entered statement goes.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum InsertAtDto {
    #[serde(rename_all = "camelCase")]
    Before { event: String },
    #[serde(rename_all = "camelCase")]
    After { event: String },
    #[serde(rename_all = "camelCase")]
    EndOfVoice { part: String, voice: String },
}

impl From<InsertAtDto> for InsertAt {
    fn from(at: InsertAtDto) -> Self {
        match at {
            InsertAtDto::Before { event } => Self::Before { event },
            InsertAtDto::After { event } => Self::After { event },
            InsertAtDto::EndOfVoice { part, voice } => Self::EndOfVoice { part, voice },
        }
    }
}

/// What to write: pitches and durations as the language spells them.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum NoteSpecDto {
    #[serde(rename_all = "camelCase")]
    Note { pitch: String, duration: String },
    #[serde(rename_all = "camelCase")]
    Rest { duration: String },
    #[serde(rename_all = "camelCase")]
    Chord { pitches: Vec<String>, duration: String },
}

impl From<NoteSpecDto> for NoteSpec {
    fn from(note: NoteSpecDto) -> Self {
        match note {
            NoteSpecDto::Note { pitch, duration } => Self::Note { pitch, duration },
            NoteSpecDto::Rest { duration } => Self::Rest { duration },
            NoteSpecDto::Chord { pitches, duration } => Self::Chord { pitches, duration },
        }
    }
}

/// A structured score edit from the webview (roadmap §11).
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum EditDto {
    #[serde(rename_all = "camelCase")]
    InsertNote { at: InsertAtDto, note: NoteSpecDto },
    #[serde(rename_all = "camelCase")]
    ChangePitch {
        event: String,
        pitch: String,
        mode: GeneratedEditModeDto,
    },
    #[serde(rename_all = "camelCase")]
    ChangeDuration {
        event: String,
        duration: String,
        mode: GeneratedEditModeDto,
    },
    #[serde(rename_all = "camelCase")]
    ExtractMotif { events: Vec<String>, name: String },
    #[serde(rename_all = "camelCase")]
    SetHeader { field: HeaderFieldDto, value: String },
}

impl From<EditDto> for EditCommand {
    fn from(edit: EditDto) -> Self {
        match edit {
            EditDto::InsertNote { at, note } => Self::InsertNote {
                at: at.into(),
                note: note.into(),
            },
            EditDto::ChangePitch { event, pitch, mode } => Self::ChangePitch {
                event,
                pitch,
                mode: mode.into(),
            },
            EditDto::ChangeDuration { event, duration, mode } => Self::ChangeDuration {
                event,
                duration,
                mode: mode.into(),
            },
            EditDto::ExtractMotif { events, name } => Self::ExtractMotif { events, name },
            EditDto::SetHeader { field, value } => Self::SetHeader {
                field: field.into(),
                value,
            },
        }
    }
}

/// Which of the piece's own header statements a `SetHeader` edit is for.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum HeaderFieldDto {
    Title,
    Subtitle,
    Composer,
    Arranger,
    Copyright,
    Tempo,
    Meter,
    Key,
}

impl From<HeaderFieldDto> for HeaderField {
    fn from(field: HeaderFieldDto) -> Self {
        match field {
            HeaderFieldDto::Title => Self::Title,
            HeaderFieldDto::Subtitle => Self::Subtitle,
            HeaderFieldDto::Composer => Self::Composer,
            HeaderFieldDto::Arranger => Self::Arranger,
            HeaderFieldDto::Copyright => Self::Copyright,
            HeaderFieldDto::Tempo => Self::Tempo,
            HeaderFieldDto::Meter => Self::Meter,
            HeaderFieldDto::Key => Self::Key,
        }
    }
}

/// Which of the studio's three namespaces a container lives in.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ContainerKindDto {
    Patch,
    Bus,
    Signal,
}

impl From<ContainerKindDto> for ContainerKind {
    fn from(kind: ContainerKindDto) -> Self {
        match kind {
            ContainerKindDto::Patch => Self::Patch,
            ContainerKindDto::Bus => Self::Bus,
            ContainerKindDto::Signal => Self::Signal,
        }
    }
}

/// A structured studio edit from the webview — a source-owned sound choice,
/// knob, or fader (roadmap §11, §14.4).
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum StudioEditDto {
    #[serde(rename_all = "camelCase")]
    ChooseSound {
        part: String,
        instrument: String,
        profile: String,
    },
    #[serde(rename_all = "camelCase")]
    MakeSoundExplicit { part: String },
    SetParam {
        container: ContainerKindDto,
        name: String,
        stage: usize,
        param: String,
        value: f64,
    },
    #[serde(rename_all = "camelCase")]
    SetSendLevel { source: String, bus: String, decibels: f64 },
}

impl From<StudioEditDto> for StudioEdit {
    fn from(edit: StudioEditDto) -> Self {
        match edit {
            StudioEditDto::ChooseSound {
                part,
                instrument,
                profile,
            } => Self::ChooseSound {
                part,
                instrument,
                profile,
            },
            StudioEditDto::MakeSoundExplicit { part } => Self::MakeSoundExplicit { part },
            StudioEditDto::SetParam {
                container,
                name,
                stage,
                param,
                value,
            } => Self::SetParam {
                kind: container.into(),
                container: name,
                stage,
                param,
                value,
            },
            StudioEditDto::SetSendLevel { source, bus, decibels } => Self::SetSendLevel { source, bus, decibels },
        }
    }
}

impl CommandDto {
    /// The session request this stands for.
    ///
    /// The mapping lives here, on the exhaustive match, so a new variant is a
    /// compile error rather than a request that silently does nothing.
    pub(crate) fn into_request(self) -> Request {
        match self {
            Self::SetSource { source } => Request::Command(ProjectCommand::SetSource(source)),
            Self::ApplyEdits { edits } => {
                Request::Command(ProjectCommand::ApplyEdits(edits.into_iter().map(Into::into).collect()))
            }
            Self::EditScore { edit } => Request::Command(ProjectCommand::EditScore(edit.into())),
            Self::EditStudio { edit } => Request::Command(ProjectCommand::EditStudio(edit.into())),
            Self::Format => Request::Command(ProjectCommand::Format),
            Self::InsertBarlines { revision } => Request::Command(ProjectCommand::InsertBarlines {
                revision: musa_project::Revision(revision),
            }),
            Self::ApplyGroupEdit { plan, revision } => Request::Command(ProjectCommand::ApplyGroupEdit {
                plan,
                revision: musa_project::Revision(revision),
            }),
            Self::Save => Request::Command(ProjectCommand::Save),
            Self::RestoreRecovery => Request::Command(ProjectCommand::RestoreRecovery),
            Self::DiscardRecovery => Request::Command(ProjectCommand::DiscardRecovery),
            Self::Undo => Request::Undo,
            Self::Redo => Request::Redo,
            Self::NewPerformance { performance } => Request::Command(ProjectCommand::NewPerformance { performance }),
            Self::Keep { decision } => Request::Command(ProjectCommand::Pin(decision)),
            Self::Release { decision } => Request::Command(ProjectCommand::Unpin(decision)),
        }
    }
}

/// A transport request from the webview.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum TransportDto {
    Play,
    Stop,
    #[serde(rename_all = "camelCase")]
    Seek {
        frame: u64,
    },
    #[serde(rename_all = "camelCase")]
    SetLoop {
        start: u64,
        end: u64,
    },
    ClearLoop,
}

impl From<TransportDto> for TransportRequest {
    fn from(request: TransportDto) -> Self {
        match request {
            TransportDto::Play => Self::Play,
            TransportDto::Stop => Self::Stop,
            TransportDto::Seek { frame } => Self::Seek { frame },
            TransportDto::SetLoop { start, end } => Self::SetLoop { start, end },
            TransportDto::ClearLoop => Self::ClearLoop,
        }
    }
}

/// What to export, and where to put it.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ExportDto {
    pub target: ExportTargetDto,
    /// Absent means ask the user where to put it.
    pub path: Option<String>,
}

/// The export formats the shell offers.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ExportTargetDto {
    Mei,
    LilyPond,
    MusicXml,
    Wav,
}

impl From<ExportTargetDto> for ExportRequest {
    fn from(target: ExportTargetDto) -> Self {
        match target {
            ExportTargetDto::Mei => Self::Mei,
            ExportTargetDto::LilyPond => Self::LilyPond,
            ExportTargetDto::MusicXml => Self::MusicXml,
            ExportTargetDto::Wav => Self::Wav,
        }
    }
}

/// What a new piece starts as.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum TemplateDto {
    /// A short piece that is immediately playable (roadmap §14.8).
    #[default]
    Piece,
    Empty,
}

impl From<TemplateDto> for Template {
    fn from(template: TemplateDto) -> Self {
        match template {
            TemplateDto::Piece => Self::Piece,
            TemplateDto::Empty => Self::Empty,
        }
    }
}

/// A failure, in the interface's own vocabulary.
///
/// `05-states.md` §1: errors say what is wrong and where, and never
/// apologize. `kind` exists so the webview can decide *where* to put the
/// message — a rejected edit belongs in the source column, an unreadable file
/// belongs in the top margin — without parsing the sentence.
#[derive(Clone, Debug, Deserialize, Serialize, TS, thiserror::Error)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
#[error("{message}")]
pub struct ErrorDto {
    pub kind: ErrorKindDto,
    pub message: String,
}

/// Which surface a failure belongs on.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ErrorKindDto {
    /// The file could not be read or written.
    File,
    /// The document refused the edit.
    Document,
    /// There is nothing to undo, redo, or export yet.
    Nothing,
    /// A backend — notation, performance, or audio — failed.
    Backend,
}

impl From<&ProjectError> for ErrorDto {
    fn from(error: &ProjectError) -> Self {
        let kind = match *error {
            ProjectError::Io { .. }
            | ProjectError::NoPieces { .. }
            | ProjectError::Assets(_)
            | ProjectError::Packages(_) => ErrorKindDto::File,
            ProjectError::RejectedEdit { .. }
            | ProjectError::BarlineRewrite(_)
            | ProjectError::NoSuchEvent(_)
            | ProjectError::Uneditable(_)
            | ProjectError::NotYetImplemented { .. }
            // An analysis request that named a part or a window this score
            // does not have is a mistake about the document, not a backend
            // that failed: nothing was attempted.
            | ProjectError::Analysis(_) => ErrorKindDto::Document,
            ProjectError::NothingTo(_) | ProjectError::NoValidScore => ErrorKindDto::Nothing,
            ProjectError::Performance(_)
            | ProjectError::Notation(_)
            | ProjectError::Engine(_)
            | ProjectError::Events(_) => ErrorKindDto::Backend,
        };
        Self {
            kind,
            message: error.to_string(),
        }
    }
}

impl ErrorDto {
    /// A failure the shell itself is responsible for.
    pub(crate) fn shell(kind: ErrorKindDto, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
        }
    }
}

/// Where an export landed, so the interface can say so by name.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ExportedDto {
    pub path: String,
}

impl From<PathBuf> for ExportedDto {
    fn from(path: PathBuf) -> Self {
        Self {
            path: path.display().to_string(),
        }
    }
}

/// Which measured disagreement a review mark stands for.
///
/// One variant per class prompt 203 observed in the corpus; the interface has
/// no mark it cannot name.
#[derive(Clone, Copy, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum AmbiguityKindDto {
    Pulse,
    Phase,
    Placement,
    WrittenEnd,
    OnsetGroup,
    Voice,
    Spelling,
}

impl From<musa_project::AmbiguityKind> for AmbiguityKindDto {
    fn from(kind: musa_project::AmbiguityKind) -> Self {
        match kind {
            musa_project::AmbiguityKind::Pulse => Self::Pulse,
            musa_project::AmbiguityKind::Phase => Self::Phase,
            musa_project::AmbiguityKind::Placement => Self::Placement,
            musa_project::AmbiguityKind::WrittenEnd => Self::WrittenEnd,
            musa_project::AmbiguityKind::OnsetGroup => Self::OnsetGroup,
            musa_project::AmbiguityKind::Voice => Self::Voice,
            musa_project::AmbiguityKind::Spelling => Self::Spelling,
        }
    }
}

/// Which performance the transport would play in Review.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ReviewAuditionDto {
    /// The captured timing, exactly as played.
    Played,
    /// The proposed notation, through the ordinary performance path.
    Written,
}

impl From<ReviewAuditionDto> for ReviewAudition {
    fn from(mode: ReviewAuditionDto) -> Self {
        match mode {
            ReviewAuditionDto::Played => Self::Played,
            ReviewAuditionDto::Written => Self::Written,
        }
    }
}

impl From<ReviewAudition> for ReviewAuditionDto {
    fn from(mode: ReviewAudition) -> Self {
        match mode {
            ReviewAudition::Played => Self::Played,
            ReviewAudition::Written => Self::Written,
        }
    }
}

/// One reading a review mark offers.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ReviewChoiceDto {
    pub id: String,
    pub label: String,
    pub current: bool,
}

/// One location still asking for a decision.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ReviewAmbiguityDto {
    pub id: String,
    pub kind: AmbiguityKindDto,
    pub explanation: String,
    /// Proposal-note indices this mark covers.
    pub notes: Vec<u32>,
    pub choices: Vec<ReviewChoiceDto>,
}

/// One proposed note as Review draws it.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ReviewNoteDto {
    pub pitch: String,
    pub voice: u8,
    /// Grid ticks, 24 to the quarter. The frontend positions with these and
    /// never recomputes a duration from them.
    pub onset_ticks: u32,
    pub end_ticks: u32,
    pub pedal_extended: bool,
    pub grace: bool,
    /// The musical accessible name, composed by the project.
    pub name: String,
}

/// Everything the Review surface reads.
#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ReviewFactsDto {
    pub take_name: String,
    pub revision: u64,
    /// Whether the review still describes the session's revision.
    pub current: bool,
    pub meter: String,
    pub policy: String,
    pub notes: Vec<ReviewNoteDto>,
    pub voice_count: u32,
    pub ambiguities: Vec<ReviewAmbiguityDto>,
    pub losses: Vec<String>,
    pub history: Vec<String>,
    pub audition: ReviewAuditionDto,
    /// The checked source preview, absent while some length has no exact
    /// written form.
    pub source: Option<String>,
    pub sealed: bool,
    /// The notes that read differently after the last decision — one spoken
    /// result, not one per re-engraved note.
    pub changed: Vec<u32>,
}

impl From<&musa_project::ReviewFacts> for ReviewFactsDto {
    fn from(facts: &musa_project::ReviewFacts) -> Self {
        Self {
            take_name: facts.take_name.clone(),
            revision: facts.revision.0,
            current: facts.current,
            meter: facts.meter.clone(),
            policy: facts.policy.clone(),
            notes: facts
                .notes
                .iter()
                .map(|note| ReviewNoteDto {
                    pitch: note.pitch.clone(),
                    voice: note.voice,
                    onset_ticks: note.onset_ticks,
                    end_ticks: note.end_ticks,
                    pedal_extended: note.pedal_extended,
                    grace: note.grace,
                    name: note.name.clone(),
                })
                .collect(),
            voice_count: u32::try_from(facts.voice_count).unwrap_or(u32::MAX),
            ambiguities: facts
                .ambiguities
                .iter()
                .map(|mark| ReviewAmbiguityDto {
                    id: mark.id.clone(),
                    kind: mark.kind.into(),
                    explanation: mark.explanation.clone(),
                    notes: mark
                        .notes
                        .iter()
                        .map(|&note| u32::try_from(note).unwrap_or(u32::MAX))
                        .collect(),
                    choices: mark
                        .choices
                        .iter()
                        .map(|choice| ReviewChoiceDto {
                            id: choice.id.clone(),
                            label: choice.label.clone(),
                            current: choice.current,
                        })
                        .collect(),
                })
                .collect(),
            losses: facts.losses.clone(),
            history: facts.history.clone(),
            audition: facts.audition.into(),
            source: facts.source.clone(),
            sealed: facts.sealed,
            changed: facts
                .changed
                .iter()
                .map(|&note| u32::try_from(note).unwrap_or(u32::MAX))
                .collect(),
        }
    }
}

/// One gesture on the Review surface.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ReviewActionDto {
    /// Take one of the readings a mark offers.
    #[serde(rename_all = "camelCase")]
    Choose { ambiguity: String, choice: String },
    /// Beats tapped while auditioning, in take-relative microseconds.
    #[serde(rename_all = "camelCase")]
    Tap {
        beats_micros: Vec<u64>,
        downbeat: Option<u32>,
    },
    /// One of the score's own musical commands, against proposal notes.
    #[serde(rename_all = "camelCase")]
    Transform { notes: Vec<u32>, intent: GroupIntentDto },
    /// Put these notes in this line.
    #[serde(rename_all = "camelCase")]
    AssignVoice { notes: Vec<u32>, voice: u8 },
    /// Write this note with one of its offered spellings.
    #[serde(rename_all = "camelCase")]
    Respell { note: u32, pitch: String },
    /// Write this note through to the next onset in its line, or stop it at
    /// the key release.
    #[serde(rename_all = "camelCase")]
    Tie { note: u32, tied: bool },
    /// Read this onset cluster as one chord.
    #[serde(rename_all = "camelCase")]
    MakeChord { group: u32 },
    /// Read it as the separately placed notes that were played.
    #[serde(rename_all = "camelCase")]
    Split { group: u32 },
}

impl From<ReviewActionDto> for ReviewAction {
    fn from(action: ReviewActionDto) -> Self {
        match action {
            ReviewActionDto::Choose { ambiguity, choice } => Self::Choose { ambiguity, choice },
            ReviewActionDto::Tap { beats_micros, downbeat } => Self::Tap {
                beats_micros,
                downbeat: downbeat.map(|index| index as usize),
            },
            ReviewActionDto::Transform { notes, intent } => Self::Transform {
                notes: notes.into_iter().map(|note| note as usize).collect(),
                intent: intent.into(),
            },
            ReviewActionDto::AssignVoice { notes, voice } => Self::AssignVoice {
                notes: notes.into_iter().map(|note| note as usize).collect(),
                voice,
            },
            ReviewActionDto::Respell { note, pitch } => Self::Respell {
                note: note as usize,
                pitch,
            },
            ReviewActionDto::Tie { note, tied } => Self::Tie {
                note: note as usize,
                tied,
            },
            ReviewActionDto::MakeChord { group } => Self::MakeChord { group: group as usize },
            ReviewActionDto::Split { group } => Self::Split { group: group as usize },
        }
    }
}

#[cfg(test)]
mod dto_laws {
    use musa_project::ProjectSession;

    use super::{
        CommandDto, ErrorDto, ErrorKindDto, ExportDto, ExportTargetDto, ProjectError, SpanDto, TextEditDto,
        TransportDto,
    };

    type Result = std::result::Result<(), serde_json::Error>;

    /// Every command the webview can send survives the wire unchanged. The
    /// generated TypeScript is what the webview builds these from, so the tag
    /// and the field names are the contract, not an implementation detail.
    #[test]
    fn command_survives_a_round_trip() -> Result {
        let commands = [
            CommandDto::SetSource {
                source: "piece {}".to_owned(),
            },
            CommandDto::ApplyEdits {
                edits: vec![TextEditDto {
                    span: SpanDto { start: 3, end: 7 },
                    replacement: "c4".to_owned(),
                }],
            },
            CommandDto::Format,
            CommandDto::InsertBarlines { revision: 7 },
            CommandDto::Save,
            CommandDto::Undo,
            CommandDto::Redo,
        ];
        for command in commands {
            let json = serde_json::to_string(&command)?;
            let back: CommandDto = serde_json::from_str(&json)?;
            assert_eq!(format!("{command:?}"), format!("{back:?}"), "round trip of {json}");
        }
        Ok(())
    }

    /// The tag the webview writes is the one the shell reads.
    #[test]
    fn command_is_tagged_by_kind_in_camel_case() -> Result {
        let json = serde_json::to_value(CommandDto::SetSource { source: "x".to_owned() })?;
        assert_eq!(json.get("kind").and_then(serde_json::Value::as_str), Some("setSource"));
        assert_eq!(json.get("source").and_then(serde_json::Value::as_str), Some("x"));
        Ok(())
    }

    #[test]
    fn transport_survives_a_round_trip() -> Result {
        let requests = [
            TransportDto::Play,
            TransportDto::Stop,
            TransportDto::Seek { frame: 44_100 },
            TransportDto::SetLoop { start: 0, end: 96_000 },
            TransportDto::ClearLoop,
        ];
        for request in requests {
            let json = serde_json::to_string(&request)?;
            let back: TransportDto = serde_json::from_str(&json)?;
            assert_eq!(format!("{request:?}"), format!("{back:?}"), "round trip of {json}");
        }
        Ok(())
    }

    #[test]
    fn export_request_survives_a_round_trip() -> Result {
        let request = ExportDto {
            target: ExportTargetDto::LilyPond,
            path: Some("/tmp/x.ly".to_owned()),
        };
        let json = serde_json::to_string(&request)?;
        assert_eq!(json, r#"{"target":"lilyPond","path":"/tmp/x.ly"}"#);
        let back: ExportDto = serde_json::from_str(&json)?;
        assert_eq!(format!("{request:?}"), format!("{back:?}"));
        Ok(())
    }

    /// A missing destination is a distinct state from a chosen one: the
    /// webview asks for a file dialog by leaving it out.
    #[test]
    fn export_without_a_path_deserializes() -> Result {
        let request: ExportDto = serde_json::from_str(r#"{"target":"mei"}"#)?;
        assert!(request.path.is_none());
        Ok(())
    }

    /// The webview decides where to put a message from `kind` alone; it must
    /// never have to read the sentence.
    #[test]
    fn errors_classify_by_where_they_belong() {
        let cases = [
            (ProjectError::NothingTo("undo"), ErrorKindDto::Nothing),
            (ProjectError::NoValidScore, ErrorKindDto::Nothing),
            (ProjectError::Notation("bad".to_owned()), ErrorKindDto::Backend),
            (ProjectError::Engine("gone".to_owned()), ErrorKindDto::Backend),
            (ProjectError::Performance("late".to_owned()), ErrorKindDto::Backend),
            (
                ProjectError::RejectedEdit {
                    intent: "typing".to_owned(),
                    reason: "x".to_owned(),
                },
                ErrorKindDto::Document,
            ),
        ];
        for (error, expected) in cases {
            let dto = ErrorDto::from(&error);
            assert_eq!(
                format!("{:?}", dto.kind),
                format!("{expected:?}"),
                "classifying {error:?}"
            );
            assert!(!dto.message.is_empty(), "{error:?} must say something");
        }
    }

    /// An unreadable file belongs in the top margin, not in the source column.
    #[test]
    fn unreadable_files_are_file_failures() {
        let failure = ProjectSession::open(std::path::Path::new("/nonexistent/piece.musa")).err();
        let kind = failure.as_ref().map(|error| ErrorDto::from(error).kind);
        assert!(
            matches!(kind, Some(ErrorKindDto::File)),
            "a missing file must be a file failure"
        );
    }
}
