//! The wire types the webview sends in, and the one it gets back on failure.
//!
//! These are the shell's own types, not re-exported internals: the command
//! surface is allowed to grow by adding a field here, and `musa-project` is
//! never bent into a shape that exists only for a webview. Their TypeScript
//! is generated by `ts-rs` (`cargo test -p musa-desktop`), so the two sides
//! cannot drift.
//!
//! The snapshot travels the other way and is `musa-project`'s own
//! serialization — see the module documentation on [`crate::session`] for why
//! mirroring it here would create the drift this rule exists to prevent.

use std::path::PathBuf;

use musa_project::{
    EditCommand, ExportRequest, GeneratedEditMode, InsertAt, NoteSpec, ProjectCommand, ProjectError, Span, Template,
    TextEdit, TransportRequest,
};
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::session::Request;

/// A span of the source, in byte offsets.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct SpanDto {
    pub start: u32,
    pub end: u32,
}

impl From<SpanDto> for Span {
    fn from(span: SpanDto) -> Self {
        Self {
            start: span.start,
            end: span.end,
        }
    }
}

/// One replacement against the current source.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct TextEditDto {
    pub span: SpanDto,
    pub replacement: String,
}

impl From<TextEditDto> for TextEdit {
    fn from(edit: TextEditDto) -> Self {
        Self::new(edit.span.into(), edit.replacement)
    }
}

/// What the user just did to the document.
///
/// Undo and redo are here rather than on `ProjectCommand` because the session
/// exposes them as history navigation, not as edits; from the webview's side
/// they are the same kind of request and belong on the same call.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum CommandDto {
    #[serde(rename_all = "camelCase")]
    SetSource {
        source: String,
    },
    #[serde(rename_all = "camelCase")]
    ApplyEdits {
        edits: Vec<TextEditDto>,
    },
    #[serde(rename_all = "camelCase")]
    EditScore {
        edit: EditDto,
    },
    Format,
    Save,
    Undo,
    Redo,
}

/// What to do when the edited event came out of an expansion (roadmap §9).
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum GeneratedEditModeDto {
    /// Rewrite the motif; every occurrence changes.
    EditDefinition,
    /// Give this occurrence its own copy — prompt 34.
    Specialize,
}

impl From<GeneratedEditModeDto> for GeneratedEditMode {
    fn from(mode: GeneratedEditModeDto) -> Self {
        match mode {
            GeneratedEditModeDto::EditDefinition => Self::EditDefinition,
            GeneratedEditModeDto::Specialize => Self::Specialize,
        }
    }
}

/// Where a newly entered statement goes.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum InsertAtDto {
    #[serde(rename_all = "camelCase")]
    Before { event: String },
    #[serde(rename_all = "camelCase")]
    After { event: String },
    #[serde(rename_all = "camelCase")]
    EndOfVoice { part: String, voice: String },
}

impl From<InsertAtDto> for InsertAt {
    fn from(at: InsertAtDto) -> Self {
        match at {
            InsertAtDto::Before { event } => Self::Before { event },
            InsertAtDto::After { event } => Self::After { event },
            InsertAtDto::EndOfVoice { part, voice } => Self::EndOfVoice { part, voice },
        }
    }
}

/// What to write: pitches and durations as the language spells them.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum NoteSpecDto {
    #[serde(rename_all = "camelCase")]
    Note { pitch: String, duration: String },
    #[serde(rename_all = "camelCase")]
    Rest { duration: String },
    #[serde(rename_all = "camelCase")]
    Chord { pitches: Vec<String>, duration: String },
}

impl From<NoteSpecDto> for NoteSpec {
    fn from(note: NoteSpecDto) -> Self {
        match note {
            NoteSpecDto::Note { pitch, duration } => Self::Note { pitch, duration },
            NoteSpecDto::Rest { duration } => Self::Rest { duration },
            NoteSpecDto::Chord { pitches, duration } => Self::Chord { pitches, duration },
        }
    }
}

/// A structured score edit from the webview (roadmap §11).
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum EditDto {
    #[serde(rename_all = "camelCase")]
    InsertNote { at: InsertAtDto, note: NoteSpecDto },
    #[serde(rename_all = "camelCase")]
    ChangePitch {
        event: String,
        pitch: String,
        mode: GeneratedEditModeDto,
    },
    #[serde(rename_all = "camelCase")]
    ChangeDuration {
        event: String,
        duration: String,
        mode: GeneratedEditModeDto,
    },
    #[serde(rename_all = "camelCase")]
    ExtractMotif { events: Vec<String>, name: String },
}

impl From<EditDto> for EditCommand {
    fn from(edit: EditDto) -> Self {
        match edit {
            EditDto::InsertNote { at, note } => Self::InsertNote {
                at: at.into(),
                note: note.into(),
            },
            EditDto::ChangePitch { event, pitch, mode } => Self::ChangePitch {
                event,
                pitch,
                mode: mode.into(),
            },
            EditDto::ChangeDuration { event, duration, mode } => Self::ChangeDuration {
                event,
                duration,
                mode: mode.into(),
            },
            EditDto::ExtractMotif { events, name } => Self::ExtractMotif { events, name },
        }
    }
}

impl CommandDto {
    /// The session request this stands for.
    ///
    /// The mapping lives here, on the exhaustive match, so a new variant is a
    /// compile error rather than a request that silently does nothing.
    pub(crate) fn into_request(self) -> Request {
        match self {
            Self::SetSource { source } => Request::Command(ProjectCommand::SetSource(source)),
            Self::ApplyEdits { edits } => {
                Request::Command(ProjectCommand::ApplyEdits(edits.into_iter().map(Into::into).collect()))
            }
            Self::EditScore { edit } => Request::Command(ProjectCommand::EditScore(edit.into())),
            Self::Format => Request::Command(ProjectCommand::Format),
            Self::Save => Request::Command(ProjectCommand::Save),
            Self::Undo => Request::Undo,
            Self::Redo => Request::Redo,
        }
    }
}

/// A transport request from the webview.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum TransportDto {
    Play,
    Stop,
    #[serde(rename_all = "camelCase")]
    Seek {
        frame: u64,
    },
    #[serde(rename_all = "camelCase")]
    SetLoop {
        start: u64,
        end: u64,
    },
    ClearLoop,
}

impl From<TransportDto> for TransportRequest {
    fn from(request: TransportDto) -> Self {
        match request {
            TransportDto::Play => Self::Play,
            TransportDto::Stop => Self::Stop,
            TransportDto::Seek { frame } => Self::Seek { frame },
            TransportDto::SetLoop { start, end } => Self::SetLoop { start, end },
            TransportDto::ClearLoop => Self::ClearLoop,
        }
    }
}

/// What to export, and where to put it.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ExportDto {
    pub target: ExportTargetDto,
    /// Absent means ask the user where to put it.
    pub path: Option<String>,
}

/// The export formats the shell offers.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ExportTargetDto {
    Mei,
    LilyPond,
    Wav,
}

impl From<ExportTargetDto> for ExportRequest {
    fn from(target: ExportTargetDto) -> Self {
        match target {
            ExportTargetDto::Mei => Self::Mei,
            ExportTargetDto::LilyPond => Self::LilyPond,
            ExportTargetDto::Wav => Self::Wav,
        }
    }
}

/// What a new piece starts as.
#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum TemplateDto {
    /// A short piece that is immediately playable (roadmap §14.8).
    #[default]
    Piece,
    Empty,
}

impl From<TemplateDto> for Template {
    fn from(template: TemplateDto) -> Self {
        match template {
            TemplateDto::Piece => Self::Piece,
            TemplateDto::Empty => Self::Empty,
        }
    }
}

/// A failure, in the interface's own vocabulary.
///
/// `05-states.md` §1: errors say what is wrong and where, and never
/// apologize. `kind` exists so the webview can decide *where* to put the
/// message — a rejected edit belongs in the drawer, an unreadable file
/// belongs in the top margin — without parsing the sentence.
#[derive(Clone, Debug, Deserialize, Serialize, TS, thiserror::Error)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
#[error("{message}")]
pub struct ErrorDto {
    pub kind: ErrorKindDto,
    pub message: String,
}

/// Which surface a failure belongs on.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub enum ErrorKindDto {
    /// The file could not be read or written.
    File,
    /// The document refused the edit.
    Document,
    /// There is nothing to undo, redo, or export yet.
    Nothing,
    /// A backend — notation, performance, or audio — failed.
    Backend,
}

impl From<&ProjectError> for ErrorDto {
    fn from(error: &ProjectError) -> Self {
        let kind = match *error {
            ProjectError::Io { .. } => ErrorKindDto::File,
            ProjectError::RejectedEdit { .. }
            | ProjectError::NoSuchEvent(_)
            | ProjectError::Uneditable(_)
            | ProjectError::NotYetImplemented { .. } => ErrorKindDto::Document,
            ProjectError::NothingTo(_) | ProjectError::NoValidScore => ErrorKindDto::Nothing,
            ProjectError::Performance(_) | ProjectError::Notation(_) | ProjectError::Engine(_) => ErrorKindDto::Backend,
        };
        Self {
            kind,
            message: error.to_string(),
        }
    }
}

impl ErrorDto {
    /// A failure the shell itself is responsible for.
    pub(crate) fn shell(kind: ErrorKindDto, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: message.into(),
        }
    }
}

/// Where an export landed, so the interface can say so by name.
#[derive(Clone, Debug, Deserialize, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../../ui/src/lib/session/generated/")]
pub struct ExportedDto {
    pub path: String,
}

impl From<PathBuf> for ExportedDto {
    fn from(path: PathBuf) -> Self {
        Self {
            path: path.display().to_string(),
        }
    }
}

#[cfg(test)]
mod dto_laws {
    use musa_project::ProjectSession;

    use super::{
        CommandDto, ErrorDto, ErrorKindDto, ExportDto, ExportTargetDto, ProjectError, SpanDto, TextEditDto,
        TransportDto,
    };

    type Result = std::result::Result<(), serde_json::Error>;

    /// Every command the webview can send survives the wire unchanged. The
    /// generated TypeScript is what the webview builds these from, so the tag
    /// and the field names are the contract, not an implementation detail.
    #[test]
    fn command_survives_a_round_trip() -> Result {
        let commands = [
            CommandDto::SetSource {
                source: "piece {}".to_owned(),
            },
            CommandDto::ApplyEdits {
                edits: vec![TextEditDto {
                    span: SpanDto { start: 3, end: 7 },
                    replacement: "c4".to_owned(),
                }],
            },
            CommandDto::Format,
            CommandDto::Save,
            CommandDto::Undo,
            CommandDto::Redo,
        ];
        for command in commands {
            let json = serde_json::to_string(&command)?;
            let back: CommandDto = serde_json::from_str(&json)?;
            assert_eq!(format!("{command:?}"), format!("{back:?}"), "round trip of {json}");
        }
        Ok(())
    }

    /// The tag the webview writes is the one the shell reads.
    #[test]
    fn command_is_tagged_by_kind_in_camel_case() -> Result {
        let json = serde_json::to_value(CommandDto::SetSource { source: "x".to_owned() })?;
        assert_eq!(json.get("kind").and_then(serde_json::Value::as_str), Some("setSource"));
        assert_eq!(json.get("source").and_then(serde_json::Value::as_str), Some("x"));
        Ok(())
    }

    #[test]
    fn transport_survives_a_round_trip() -> Result {
        let requests = [
            TransportDto::Play,
            TransportDto::Stop,
            TransportDto::Seek { frame: 44_100 },
            TransportDto::SetLoop { start: 0, end: 96_000 },
            TransportDto::ClearLoop,
        ];
        for request in requests {
            let json = serde_json::to_string(&request)?;
            let back: TransportDto = serde_json::from_str(&json)?;
            assert_eq!(format!("{request:?}"), format!("{back:?}"), "round trip of {json}");
        }
        Ok(())
    }

    #[test]
    fn export_request_survives_a_round_trip() -> Result {
        let request = ExportDto {
            target: ExportTargetDto::LilyPond,
            path: Some("/tmp/x.ly".to_owned()),
        };
        let json = serde_json::to_string(&request)?;
        assert_eq!(json, r#"{"target":"lilyPond","path":"/tmp/x.ly"}"#);
        let back: ExportDto = serde_json::from_str(&json)?;
        assert_eq!(format!("{request:?}"), format!("{back:?}"));
        Ok(())
    }

    /// A missing destination is a distinct state from a chosen one: the
    /// webview asks for a file dialog by leaving it out.
    #[test]
    fn export_without_a_path_deserializes() -> Result {
        let request: ExportDto = serde_json::from_str(r#"{"target":"mei"}"#)?;
        assert!(request.path.is_none());
        Ok(())
    }

    /// The webview decides where to put a message from `kind` alone; it must
    /// never have to read the sentence.
    #[test]
    fn errors_classify_by_where_they_belong() {
        let cases = [
            (ProjectError::NothingTo("undo"), ErrorKindDto::Nothing),
            (ProjectError::NoValidScore, ErrorKindDto::Nothing),
            (ProjectError::Notation("bad".to_owned()), ErrorKindDto::Backend),
            (ProjectError::Engine("gone".to_owned()), ErrorKindDto::Backend),
            (ProjectError::Performance("late".to_owned()), ErrorKindDto::Backend),
            (
                ProjectError::RejectedEdit {
                    intent: "typing".to_owned(),
                    reason: "x".to_owned(),
                },
                ErrorKindDto::Document,
            ),
        ];
        for (error, expected) in cases {
            let dto = ErrorDto::from(&error);
            assert_eq!(
                format!("{:?}", dto.kind),
                format!("{expected:?}"),
                "classifying {error:?}"
            );
            assert!(!dto.message.is_empty(), "{error:?} must say something");
        }
    }

    /// An unreadable file belongs in the top margin, not in the drawer.
    #[test]
    fn unreadable_files_are_file_failures() {
        let failure = ProjectSession::open(std::path::Path::new("/nonexistent/piece.musa")).err();
        let kind = failure.as_ref().map(|error| ErrorDto::from(error).kind);
        assert!(
            matches!(kind, Some(ErrorKindDto::File)),
            "a missing file must be a file failure"
        );
    }
}
