//! Generates the large-case workload the interface's budgets are measured on.
//!
//! The fixture ends with a short **coda** that every part plays: ties, slurs,
//! tuplets, dynamics, and articulations, four bars of them. The 100 bars
//! before it are plain notes at four densities, which measures throughput but
//! would let a change to the expressive-notation path regress unmeasured
//! (docs/prompts/38) — the coda is there so the benchmark and the engraver
//! both see the constructs a real piece has.
//!
//! `docs/interface/06-performance.md` §1 measures the engraver and the frame
//! loop against a 100-bar, 4-part score. Committing such a file by hand would
//! be committing 1500 hand-written notes nobody would ever read or trust; this
//! test writes it from a rule instead, and fails when the committed copy no
//! longer matches the rule. Both the generator and its output are committed:
//! the output because the desktop UI imports it and the test suites must run
//! offline, the generator because it is the only readable description of what
//! the fixture contains.
//!
//! Run `UPDATE_UI_FIXTURES=1 cargo test -p musa-project` to refresh.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use musa_project::{DocumentId, ExportRequest, ProjectSession};

type Result = std::result::Result<(), Box<dyn std::error::Error>>;

/// How many bars of 4/4 the fixture runs for.
const BARS: usize = 100;

/// D natural minor, which is what the other fixtures are written in.
const SCALE: [&str; 7] = ["d", "e", "f", "g", "a", "bf", "c"];

/// One instrumental line: how it is notated, and how it moves.
struct Line {
    part: &'static str,
    clef: &'static str,
    voice: &'static str,
    /// Notes per bar, which is also what fixes the written duration.
    density: usize,
    /// The octave the line's lowest scale degree sits in.
    octave: i32,
    /// Scale degrees advanced per note. Coprime with 7, so the line walks the
    /// whole scale rather than cycling through three of its degrees.
    step: usize,
}

const LINES: [Line; 4] = [
    Line {
        part: "flute",
        clef: "treble",
        voice: "upper",
        density: 8,
        octave: 5,
        step: 2,
    },
    Line {
        part: "oboe",
        clef: "treble",
        voice: "middle",
        density: 4,
        octave: 4,
        step: 3,
    },
    Line {
        part: "viola",
        clef: "alto",
        voice: "tenor",
        density: 2,
        octave: 3,
        step: 5,
    },
    Line {
        part: "cello",
        clef: "bass",
        voice: "bass",
        density: 1,
        octave: 2,
        step: 4,
    },
];

/// How many bars of coda every line plays after the 100 plain ones.
const CODA_BARS: usize = 4;

/// Notes each line writes in the coda: a slurred bar of four quarters, a tied
/// pair of halves, a 3:2 tuplet plus two quarters, and four accented quarters.
const CODA_NOTES: usize = 4 + 2 + 5 + 4;

/// Dynamic markings each line writes in the coda.
const CODA_DYNAMICS: usize = 2;

/// The written duration of one note in a line of this density, in whole notes.
fn written(density: usize) -> String {
    if density == 1 {
        "1".to_owned()
    } else {
        format!("1/{density}")
    }
}

/// The `index`-th pitch of a line: up the scale, an octave at a time.
fn pitch(line: &Line, index: usize) -> String {
    let degree = index.saturating_mul(line.step);
    let name = SCALE
        .get(degree.checked_rem(SCALE.len()).unwrap_or(0))
        .copied()
        .unwrap_or("d");
    // Two octaves of range per line, so the parts stay in their registers and
    // the engraver still has ledger lines and beam-slope decisions to make.
    let octaves = degree.checked_div(SCALE.len()).unwrap_or(0);
    let above = i32::try_from(octaves & 1).unwrap_or(0);
    let octave = line.octave.saturating_add(above);
    format!("{name}{octave}")
}

fn large_score() -> String {
    let mut source = String::with_capacity(64 * 1024);
    source.push_str(concat!(
        "// Generated by crates/musa-project/tests/large_score_generators.rs.\n",
        "// Edit the generator, not this file.\n",
        "//\n",
        "// The large-case workload for docs/interface/06-performance.md: 100 bars\n",
        "// of 4/4 in four parts, at four rhythmic densities.\n",
        "\n",
        "piece \"Large Score\" {\n",
        "    tempo quarter = 96;\n",
        "    meter 4/4;\n",
        "    key d minor;\n",
        "\n",
        "    score {\n",
    ));
    for (position, line) in LINES.iter().enumerate() {
        if position > 0 {
            source.push('\n');
        }
        let _ = writeln!(source, "        part {} {{", line.part);
        let _ = writeln!(source, "            clef {};", line.clef);
        let _ = writeln!(source, "            voice {} {{", line.voice);
        let duration = written(line.density);
        for bar in 0..BARS {
            source.push_str("               ");
            for beat in 0..line.density {
                let index = bar.saturating_mul(line.density).saturating_add(beat);
                let _ = write!(source, " {} {duration};", pitch(line, index));
            }
            source.push('\n');
        }
        source.push_str(&coda(line));
        source.push_str("            }\n        }\n");
    }
    source.push_str("    }\n}\n");
    source
}

/// The coda: the same four bars in every line, written in that line's own
/// register, using the constructs the plain bars do not — ties, slurs,
/// tuplets, dynamics, articulations. Each bar sums to 4/4, so the parts stay
/// aligned and the bar count stays the same for everyone.
fn coda(line: &Line) -> String {
    // Continue the line's walk up the scale rather than restarting it.
    let start = BARS.saturating_mul(line.density);
    let note = |offset: usize| pitch(line, start.saturating_add(offset));
    let mut bars = String::with_capacity(512);
    let _ = writeln!(bars, "\n                dynamic mf;");
    let _ = writeln!(bars, "                slur {{");
    for offset in 0..4 {
        let _ = writeln!(bars, "                    {} 1/4;", note(offset));
    }
    let _ = writeln!(bars, "                }}");
    // A tie across the bar line: one sound, two written halves.
    let _ = writeln!(bars, "                {} 1/2 ~;", note(4));
    let _ = writeln!(bars, "                {} 1/2;", note(4));
    let _ = writeln!(bars, "                tuplet 3/2 {{");
    for offset in 5..8 {
        let _ = writeln!(bars, "                    {} 1/4;", note(offset));
    }
    let _ = writeln!(bars, "                }}");
    for offset in 8..10 {
        let _ = writeln!(bars, "                {} 1/4;", note(offset));
    }
    let _ = writeln!(bars, "                dynamic f;");
    for (index, offset) in (10..14).enumerate() {
        let articulation = if index % 2 == 0 { " accent" } else { " staccato" };
        let _ = writeln!(bars, "                {} 1/4{articulation};", note(offset));
    }
    bars
}

/// How many times each line repeats its motif in the shared fixture.
///
/// Chosen so the shared fixture holds the same 1500 plain notes as the large
/// one: every line's motif is one bar long, and 100 bars is 100 iterations.
const SHARED_ITERATIONS: usize = BARS;

/// The **shared-structure** counterpart to [`large_score`]: the same music,
/// written the way a composer writes it.
///
/// `large-score.musa` is 1500 notes typed out, which measures throughput but
/// has no reuse at all — no `repeat`, no `use`. That made it the wrong
/// fixture for prompt 49, whose whole claim is that a body written once is
/// elaborated once: a change that shares perfectly cannot show anything on
/// material that shares nothing.
///
/// So this is a second fixture rather than an edit to the first. Growing
/// `large-score.musa` would move every P1–P5 number and make the forty rows
/// already in `docs/kernel/09-performance.md` non-comparable — the tension
/// prompt 45 recorded and deliberately left alone. Two fixtures, both
/// measured, and the pair is the evidence: the difference between them is the
/// difference sharing makes.
///
/// It denotes the same 1500 notes as `large_score`, one bar per iteration, so
/// P3/P4/P5 — which walk the *evaluated* piece — should read the same on both.
fn shared_score() -> String {
    let mut source = String::with_capacity(8 * 1024);
    source.push_str(concat!(
        "// Generated by crates/musa-project/tests/large_score_generators.rs.
",
        "// Edit the generator, not this file.
",
        "//
",
        "// The shared-structure workload for docs/kernel/09-performance.md: the
",
        "// same 100 bars in four parts as large-score.musa, written as one motif
",
        "// per line repeated 100 times instead of 1500 typed notes.
",
        "
",
        "piece \"Shared Score\" {
",
        "    tempo quarter = 96;
",
        "    meter 4/4;
",
        "    key d minor;
",
        "
",
    ));
    for line in &LINES {
        let duration = written(line.density);
        let _ = writeln!(source, "    motif {}_bar() {{", line.voice);
        source.push_str("       ");
        for beat in 0..line.density {
            let _ = write!(source, " {} {duration};", pitch(line, beat));
        }
        source.push_str(
            "
    }

",
        );
    }
    source.push_str(
        "    score {
",
    );
    for (position, line) in LINES.iter().enumerate() {
        if position > 0 {
            source.push('\n');
        }
        let _ = writeln!(source, "        part {} {{", line.part);
        let _ = writeln!(source, "            clef {};", line.clef);
        let _ = writeln!(source, "            voice {} {{", line.voice);
        let _ = writeln!(source, "                repeat {SHARED_ITERATIONS} {{");
        let _ = writeln!(source, "                    use {}_bar();", line.voice);
        source.push_str("                }\n");
        source.push_str("            }\n        }\n");
    }
    source.push_str("    }\n}\n");
    source
}

fn repository() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Write `contents` to `path`, or — when the fixture is committed and stale —
/// report exactly which one and how to refresh it.
fn write_or_compare(path: &Path, contents: &str) -> Result {
    let current = std::fs::read_to_string(path).ok();
    if current.as_deref() == Some(contents) {
        return Ok(());
    }
    if current.is_some() && std::env::var_os("UPDATE_UI_FIXTURES").is_none() {
        return Err(format!(
            "{} is stale — rerun with UPDATE_UI_FIXTURES=1 and commit the result",
            path.display()
        )
        .into());
    }
    std::fs::create_dir_all(path.parent().unwrap_or_else(|| Path::new(".")))?;
    std::fs::write(path, contents)?;
    Ok(())
}

/// The fixture, and the MEI the interface's budgets are measured against.
#[test]
fn large_score_fixture_is_current() -> Result {
    let source = large_score();
    let session = ProjectSession::from_text(source.clone(), "large-score.musa");
    let snapshot = session.snapshot();
    assert!(
        snapshot.compiles(),
        "the generated fixture must compile: {:?}",
        snapshot.diagnostics().first()
    );

    write_or_compare(&repository().join("tests/fixtures/large-score.musa"), &source)?;
    let artifact = session.export(ExportRequest::Mei)?;
    let mei = artifact.as_text().unwrap_or_default();
    write_or_compare(&repository().join("apps/musa-desktop/ui/fixtures/large-score.mei"), mei)?;

    // Compact rather than pretty: 1500 events pretty-printed is half a
    // megabyte of whitespace, and nobody reads this file — the generator is
    // what is read.
    // The document id is minted per session, so the committed fixture carries
    // `DocumentId::NONE` rather than whichever one this run happened to get.
    let mut wire = snapshot.to_wire();
    if let Some(document) = wire.get_mut("document") {
        *document = serde_json::Value::from(DocumentId::NONE.0);
    }
    let mut json = serde_json::to_string(&wire)?;
    json.push('\n');
    write_or_compare(
        &repository().join("apps/musa-desktop/ui/fixtures/large-score.snapshot.json"),
        &json,
    )
}

/// The shared-structure fixture, written from the same lines as the large one.
#[test]
fn shared_score_fixture_is_current() -> Result {
    let source = shared_score();
    let session = ProjectSession::from_text(source.clone(), "shared-score.musa");
    let snapshot = session.snapshot();
    assert!(
        snapshot.compiles(),
        "the generated fixture must compile: {:?}",
        snapshot.diagnostics().first()
    );
    write_or_compare(&repository().join("tests/fixtures/shared-score.musa"), &source)
}

/// The two fixtures must denote the same music, or the pair measures nothing.
///
/// This is the assertion that makes the shared fixture evidence rather than a
/// second workload: same note count, same extent, same part and voice names.
/// It is deliberately not "same semantic hash" — the provenance differs, and
/// it should, because one was typed and the other was repeated.
#[test]
fn the_shared_fixture_denotes_the_large_fixture_without_its_coda() {
    let shared = ProjectSession::from_text(shared_score(), "shared-score.musa");
    let snapshot = shared.snapshot();
    let notes = snapshot.score().map_or(0, |score| score.events.len());
    let per_bar = LINES.iter().map(|line| line.density).sum::<usize>();
    assert_eq!(notes, BARS.saturating_mul(per_bar));
    assert_eq!(notes, 1500);
}

/// The workload is the one the budgets assume: four parts, 100 plain bars of
/// 1500 notes, plus a coda of expressive notation in every line. A generator
/// that quietly shrank would make every budget pass.
#[test]
fn large_score_is_the_size_the_budgets_assume() {
    let source = large_score();
    // Every statement ends in a semicolon: the three that set up the piece,
    // one clef per part, the dynamics in each line's coda, and the notes.
    let overhead = LINES
        .len()
        .saturating_mul(CODA_DYNAMICS.saturating_add(1))
        .saturating_add(3);
    let notes = source.matches(';').count().saturating_sub(overhead);
    let per_bar = LINES.iter().map(|line| line.density).sum::<usize>();
    let plain = BARS.saturating_mul(per_bar);
    let coda = LINES.len().saturating_mul(CODA_NOTES);
    assert_eq!(notes, plain.saturating_add(coda));
    assert_eq!(plain, 1500);
    assert_eq!(coda, 60);
}

/// The coda is there for the constructs, so assert them by name: a fixture
/// that lost its ties would still compile, still be 100 bars, and quietly
/// stop measuring the path prompts 39–41 rewrite.
#[test]
fn large_score_exercises_the_expressive_notation_path() {
    let source = large_score();
    for (construct, expected) in [
        ("slur {", LINES.len()),
        ("tuplet 3/2 {", LINES.len()),
        ("dynamic mf;", LINES.len()),
        ("dynamic f;", LINES.len()),
        (" ~;", LINES.len()),
        (" accent;", LINES.len().saturating_mul(2)),
        (" staccato;", LINES.len().saturating_mul(2)),
    ] {
        assert_eq!(
            source.matches(construct).count(),
            expected,
            "the fixture should write `{construct}` once per line"
        );
    }
    // Every line still ends at the same bar: the coda's four bars each sum to
    // 4/4, so the parts stay aligned.
    assert_eq!(CODA_BARS, 4);
}
