#!/bin/sh
set -eu

# Executable map for note 72. Each selection has a negative or differential
# control; passing this script is not a claim that the paper arguments are
# mechanized.
run() {
    label=$1
    expression=$2
    printf '%s\n' "$label"
    cargo nextest run --workspace -E "$expression"
}

run 'K1-K3 normalization and conversion' \
    'test(/normalization_is_|a_normal_form_contains_no_redex|normal_forms_are_eta_long|alpha_equivalent_terms_normalize|conversion_is_|conversion_decides_each_rule|conversion_agrees_with_|nothing_is_accepted_where_conversion_says_no|exhaustion_is_not_a_negative_answer/)'
run 'K4 elaboration preservation' \
    'test(/a_program_with_no_implicits_elaborates_to_itself|an_accepted_terms_metas_are_all_solved|a_match_is_the_recursor_it_compiles_to|a_branch_is_checked_at_the_motive_instantiated_at_its_pattern/)'
run 'K5-K7 canonical forms normalization and consistency premises' \
    'test(/a_literal_and_a_base_type_are_their_own_normal_forms|a_saturated_constructor_reads_back_without_its_parameters|what_is_not_canonical_data_reads_back_as_nothing|a_numeral_and_the_tower_it_stands_for_are_one_program|a_port_that_carries_a_function_is_refused_and_names_the_type|a_call_on_a_smaller_argument_is_admitted_and_computes|a_recursion_the_measure_cannot_see_is_refused|a_declaration_is_refused_for_the_reason_it_is_wrong|an_empty_family_has_no_constructor_to_name|an_occurrence_may_sit_at_any_depth_of_positive_parameters|an_occurrence_outside_a_positive_position_is_still_refused/)'
run 'K8-K12 coverage termination and unification' \
    'test(/a_match_is_refused_for_the_reason_it_is_wrong|a_missing_constructor_is_named_by_the_declaration_group|a_recursion_that_accumulates_carries_the_argument_it_changed|a_match_on_two_subjects_descends_in_one_of_its_columns|a_recursion_may_change_the_arguments_it_does_not_descend_on|a_metavariable_determined_twice|a_solution_that_would_escape|an_inserted_implicit_is_solved|a_solution_that_is_itself_a_metavariable|a_binder_nothing_determines|elaboration_is_deterministic|a_match_whose_goal_is_a_metavariable|a_branch_that_answers_another_branchs_goal|a_match_refines_the_goal_from_the_index_it_learned/)'
run 'K13 storable boundary' \
    'test(/a_port_that_carries_a_function_is_refused_and_names_the_type|a_port_that_carries_a_declared_family_is_answered_without_being_written|a_base_type_indexed_by_a_literal_is_finite_data|a_literal_is_data_only_where_a_base_type_indexes_on_it/)'
run 'K14 track construction' \
    'test(/follow_translates_and_adds_durations|together_takes_max_duration_and_keeps_multiplicity|map_payloads_preserves_support|every_well_formed_term_evaluates|ill_formed_terms_are_rejected|a_fragment_inhabits_the_track_type_it_was_promised|two_statements_are_one_follow_the_core_accepts|a_piece_reads_back_as_the_track_it_folded|following_adds_the_durations_and_places_the_second_after_the_first|together_is_the_events_stacking|play_gives_every_fact_it_makes_the_scope_placement_and_origin_it_was_given/)'
run 'K15 musical-domain conservativity premises' \
    'test(/the_compilers_own_context_builds|every_delta_spelling_is_registered_exactly_once|the_operations_past_both_tables_are_named_and_in_neither|every_owned_operation_names_its_hidden_information|the_unregistered_rows_are_the_families_they_are_said_to_be|every_partial_exact_time_operation_states_its_own_refusal|a_destructuring_pattern_at_a_base_type_is_refused|a_rule_that_refuses_refuses_the_program|a_rule_that_answers_nothing_is_still_a_compiler_defect|two_registries_with_the_same_vocabulary_reduce_alike/)'
run 'K17 numeral conservativity' \
    'test(/a_numeral_and_the_tower_it_stands_for_are_one_program|a_numeral_of_fifty_thousand_neither_overflows_nor_deepens|any_family_of_the_counting_shape_takes_a_numeral/)'
run 'K18 evaluation and elaboration determinism' \
    'test(/normalization_is_deterministic|elaboration_is_deterministic|two_registries_with_the_same_vocabulary_reduce_alike|law_7_two_runs_of_one_transformer_agree_on_value_and_on_charge/)'
run 'K19 budget independence' \
    'test(/a_narrower_budget_exhausts_or_agrees|exhaustion_is_monotone_in_the_budget|the_language_budget_answers_every_question_in_the_corpus|a_narrow_budget_exhausts_rather_than_refusing/)'
run 'K20 kernel rechecking' \
    'test(/the_kernel_agrees_with_every_term_the_conversion_corpus_is_stated_over|the_kernel_agrees_with_every_program_elaboration_accepts|the_kernel_rejects_an_index_that_names_no_binder|the_kernel_rejects_a_term_at_the_wrong_type|the_kernel_rechecks_every_member_including_the_ones_nobody_wrote|the_kernel_rechecks_a_program_built_from_every_inferable_corpus_term|the_kernel_accepts_whatever_elaboration_produced|the_generator_reaches_programs_elaboration_accepts|the_kernel_rechecks_the_standard_library|the_kernel_rechecks_every_example/)'

./scripts/check-syntax-adapter-conformance.sh
