//! Embed the bundled standard library's source root.
//!
//! This script is deliberately stupid: it lists every `.musa` file under
//! `stdlib/src` and writes one `include_str!` per file. It decides nothing
//! about what the package *contains* — that is
//! [`crate::package`]'s job, and it answers it from the `mod` declarations in
//! the source itself. Splitting it this way is what gives the package one
//! hand-edited input: a file that appears here without a `mod` reaching it is
//! not quietly importable, it is a *declared nowhere* error.
//!
//! The listing is what lets the library be read at its `musa-stdlib:` URIs
//! with no filesystem access, which the desktop and the web build both need.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../stdlib");
    let source_root = root.join("src");
    println!("cargo:rerun-if-changed={}", root.join("musa.toml").display());
    let mut files = Vec::new();
    collect(&source_root, &source_root, &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs from `stdlib/src`. Do not edit.\n\
         pub(crate) const STANDARD_LIBRARY_FILES: &[(&str, &str)] = &[\n",
    );
    for (relative, absolute) in &files {
        let _ = writeln!(out, "    ({relative:?}, include_str!({absolute:?})),");
    }
    out.push_str("];\n");

    let destination = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("stdlib_files.rs");
    std::fs::write(&destination, out).expect("write the standard-library listing");
}

/// Every `.musa` file under `directory`, as (path relative to `base`, absolute).
///
/// Directories are announced to cargo as well as files, so that *adding* a
/// file reruns this script — which is the case the whole arrangement exists to
/// catch.
fn collect(base: &Path, directory: &Path, found: &mut Vec<(String, String)>) {
    println!("cargo:rerun-if-changed={}", directory.display());
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, found);
        } else if path.extension().is_some_and(|extension| extension == "musa") {
            let relative = path
                .strip_prefix(base)
                .expect("a file under the source root")
                .to_string_lossy()
                .replace('\\', "/");
            found.push((relative, path.to_string_lossy().into_owned()));
        }
    }
}
