//! Deterministic sources for prompt 93's elaboration migration workloads.
//!
//! Run `UPDATE_ELABORATION_BASELINE=1 cargo test -p musa-compiler
//! --test elaboration_fixture_generators` to refresh the committed fixtures.

#![allow(clippy::expect_used)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use musa_compiler::{CompileOptions, SourceDocument, compile};

type Result = std::result::Result<(), Box<dyn std::error::Error>>;

const UPDATE: &str = "UPDATE_ELABORATION_BASELINE";

fn word(index: usize) -> String {
    let first = char::from(b'a'.saturating_add(u8::try_from(index / 26).unwrap_or(0)));
    let second = char::from(b'a'.saturating_add(u8::try_from(index % 26).unwrap_or(0)));
    if index < 26 {
        second.to_string()
    } else {
        format!("{first}{second}")
    }
}

fn repository() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn write_or_compare(path: &Path, contents: &str) -> Result {
    let current = std::fs::read_to_string(path).ok();
    if current.as_deref() == Some(contents) {
        return Ok(());
    }
    if current.is_some() && std::env::var_os(UPDATE).is_none() {
        return Err(format!(
            "{} is stale — rerun with {UPDATE}=1 and commit the result",
            path.display()
        )
        .into());
    }
    std::fs::create_dir_all(path.parent().unwrap_or_else(|| Path::new(".")))?;
    std::fs::write(path, contents)?;
    Ok(())
}

fn open_shape() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Current syntax only: many reusable bodies under changing contexts.\n\n\
         piece \"Open Shape Baseline\" {\n\
             tempo 1/4 = 96;\n\
             meter 4/4;\n\
             key c major;\n\n",
    );
    for index in 0..16 {
        let root = ["c", "d", "e", "f", "g", "a", "b"]
            .get(index % 7)
            .copied()
            .unwrap_or("c");
        let name = word(index);
        let _ = writeln!(source, "    motif cell_{name}() {{ {root}4/4 e4/4 g4/4 c5/4 }}");
    }
    source.push_str("\n    score {\n");
    for (part, voice, clef) in [("flute", "upper", "treble"), ("cello", "lower", "bass")] {
        let _ = writeln!(source, "        part {part} {{");
        let _ = writeln!(source, "            clef {clef};");
        let _ = writeln!(source, "            voice {voice} {{");
        for index in 0..16 {
            let name = word(index);
            if index == 4 {
                source.push_str("                key g major;\n");
            } else if index == 8 {
                source.push_str("                key f major;\n");
            } else if index == 12 {
                source.push_str("                key c major;\n");
            }
            let _ = writeln!(source, "                use cell_{name}();");
        }
        source.push_str("            }\n        }\n");
    }
    source.push_str("    }\n}\n");
    source
}

fn higher_order_shape() -> String {
    String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // The same 128 notes as open-shape, through nested current-syntax transforms.\n\n\
         piece \"Higher Order Shape Baseline\" {\n\
             tempo 1/4 = 96;\n\
             meter 4/4;\n\
             key c major;\n\n\
             motif cell() { c4/4 e4/4 g4/4 c5/4 }\n\n\
             score {\n\
                 part flute {\n\
                     clef treble;\n\
                     voice upper {\n\
                         repeat 16 {\n\
                             stretch 1 { retrograde { retrograde { use cell(); } } }\n\
                         }\n\
                     }\n\
                 }\n\
                 part cello {\n\
                     clef bass;\n\
                     voice lower {\n\
                         repeat 16 {\n\
                             invert around c4 { invert around c4 { use cell(); } }\n\
                         }\n\
                     }\n\
                 }\n\
             }\n\
         }\n",
    )
}

fn declaration_library(index: usize) -> String {
    let mut source = String::from("library {\n");
    for item in 0..16 {
        let library = word(index);
        let item = word(item);
        let _ = writeln!(
            source,
            "    motif imported_{library}_{item}() {{ c4/4 d4/4 e4/4 f4/4 }}"
        );
    }
    source.push_str("}\n");
    source
}

fn declaration_heavy() -> String {
    let mut source = String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Many small local and imported declarations, most deliberately unused.\n\n\
         piece \"Declaration Heavy Baseline\" {\n",
    );
    for index in 0..4 {
        let _ = writeln!(source, "    import \"elaboration-libraries/library-{index}.musa\";");
    }
    source.push_str("    tempo 1/4 = 96;\n    meter 4/4;\n    key c major;\n\n");
    for index in 0..48 {
        let name = word(index);
        let _ = writeln!(source, "    motif local_{name}() {{ c4/4 d4/4 e4/4 f4/4 }}");
    }
    for index in 0..16 {
        let name = word(index);
        let _ = writeln!(source, "    fragment fragment_{name} {{ g4/4 a4/4 b4/4 c5/4 }}");
    }
    source.push_str(
        "\n    score {\n\
             part ensemble {\n\
                 voice line {\n\
                     use local_a();\n\
                     use imported_a_a();\n\
                     mobile { fragment_a; fragment_b; }\n\
                 }\n\
             }\n\
         }\n\
         }\n",
    );
    source
}

fn audio_bridge() -> String {
    String::from(
        "// Generated by crates/musa-compiler/tests/elaboration_fixture_generators.rs.\n\
         // Score marks, performance profiles, studio intent, scheduling, and DSP in one fixture.\n\n\
         piece \"Audio Bridge Baseline\" {\n\
             tempo 1/4 = 60;\n\
             meter 4/4;\n\
             key c major;\n\n\
             performance {\n\
                 profile reeds {\n\
                     mark staccato { gate = 0.55; attack = 8 ms; }\n\
                     mark accent { gate = 1; attack = 2 ms; }\n\
                     dynamic p { amplitude = 0.25; }\n\
                     dynamic f { amplitude = 0.8; }\n\
                 }\n\
                 profile strings {\n\
                     mark staccato { gate = 0.7; attack = 15 ms; }\n\
                     mark accent { gate = 1; attack = 5 ms; }\n\
                     dynamic p { amplitude = 0.2; }\n\
                     dynamic f { amplitude = 0.7; }\n\
                 }\n\
             }\n\n\
             score {\n\
                 part oboe {\n\
                     profile reeds;\n\
                     voice melody {\n\
                         dynamic p;\n\
                         crescendo to f { c5/4 staccato d5/4 e5/4 > f5/4 }\n\
                     }\n\
                 }\n\
                 part viola {\n\
                     profile strings;\n\
                     voice countermelody {\n\
                         dynamic f;\n\
                         diminuendo to p { c4/4 > g3/4 a3/4 staccato f3/4 }\n\
                     }\n\
                 }\n\
             }\n\n\
             studio {\n\
                 patch reed { oscillator(sine) |> lowpass(cutoff: 1800 Hz, q: 0.7) |> output; }\n\
                 patch bow { oscillator(sine, ratio: 0.5) |> envelope(adsr(attack: 15 ms, release: 300 ms)) |> output; }\n\
                 bus hall { reverb(room: 0.55, mix: 0.25); }\n\
                 lfo = oscillator(sine, frequency: 0.5 Hz) |> scale(200 Hz);\n\
                 modulate lfo -> reed.lowpass.cutoff;\n\
                 assign oboe -> reed;\n\
                 assign viola -> bow;\n\
                 route oboe -> master;\n\
                 route viola -> master;\n\
                 send oboe -> hall at -18 dB;\n\
                 send viola -> hall at -20 dB;\n\
                 route hall -> master;\n\
             }\n\
         }\n",
    )
}

#[test]
fn elaboration_baseline_fixtures_are_current() -> Result {
    let root = repository().join("tests/fixtures");
    for (name, source) in [
        ("open-shape.musa", open_shape()),
        ("higher-order-shape.musa", higher_order_shape()),
        ("declaration-heavy.musa", declaration_heavy()),
        ("audio-bridge.musa", audio_bridge()),
    ] {
        write_or_compare(&root.join(name), &source)?;
    }
    for index in 0..4 {
        write_or_compare(
            &root.join(format!("elaboration-libraries/library-{index}.musa")),
            &declaration_library(index),
        )?;
    }
    Ok(())
}

#[test]
fn shape_pair_has_the_same_denoted_note_count() {
    let count = |source: String, name: &str| {
        let compilation = compile(&SourceDocument::new(source, name), &CompileOptions::default());
        let score = compilation.snapshot().expect("generated fixture compiles");
        score
            .parts()
            .iter()
            .flat_map(|(_, part)| part.voices())
            .map(|(_, voice)| voice.events().len())
            .sum::<usize>()
    };
    assert_eq!(count(open_shape(), "open-shape"), 128);
    assert_eq!(count(higher_order_shape(), "higher-order-shape"), 128);
}
